"""initial schema

Revision ID: 3178065355ca
Revises: 
Create Date: 2026-08-19 15:58:22.572653

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3178065355ca'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('hypothesis', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('experiment_id', name=op.f('pk_experiments'))
    )
    op.create_table('samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('expected', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_samples'))
    )
    op.create_index(op.f('ix_samples_dataset_name'), 'samples', ['dataset_name'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('spec_frozen_json', sa.JSON(), nullable=False),
    sa.Column('spec_hash', sa.String(), nullable=False),
    sa.Column('git_commit', sa.String(), nullable=True),
    sa.Column('python_version', sa.String(), nullable=True),
    sa.Column('package_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('circuit_open_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name=op.f('fk_runs_experiment_id_experiments')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_runs'))
    )
    op.create_index(op.f('ix_runs_experiment_id'), 'runs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('delivered_to', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_alert_events_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events'))
    )
    op.create_index(op.f('ix_alert_events_rule'), 'alert_events', ['rule'], unique=False)
    op.create_index(op.f('ix_alert_events_run_id'), 'alert_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_alert_events_ts'), 'alert_events', ['ts'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_artifacts_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_artifacts_sha256'), 'artifacts', ['sha256'], unique=False)
    op.create_table('dlq_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('arm', sa.String(), nullable=False),
    sa.Column('rollout_idx', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_dlq_entries_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dlq_entries'))
    )
    op.create_index(op.f('ix_dlq_entries_next_retry_at'), 'dlq_entries', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_dlq_entries_run_id'), 'dlq_entries', ['run_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('labels_json', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_metrics_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics'))
    )
    op.create_index(op.f('ix_metrics_name'), 'metrics', ['name'], unique=False)
    op.create_index(op.f('ix_metrics_run_id'), 'metrics', ['run_id'], unique=False)
    op.create_index(op.f('ix_metrics_ts'), 'metrics', ['ts'], unique=False)
    op.create_table('rollouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('arm', sa.String(), nullable=False),
    sa.Column('rollout_idx', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completion', sa.String(), nullable=True),
    sa.Column('transcript_json', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd_est', sa.Float(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_rollouts_run_id_runs')),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], name=op.f('fk_rollouts_sample_id_samples')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rollouts')),
    sa.UniqueConstraint('run_id', 'sample_id', 'arm', 'rollout_idx', name='uq_rollouts_identity')
    )
    op.create_index(op.f('ix_rollouts_run_id'), 'rollouts', ['run_id'], unique=False)
    op.create_index(op.f('ix_rollouts_sample_id'), 'rollouts', ['sample_id'], unique=False)
    op.create_index(op.f('ix_rollouts_status'), 'rollouts', ['status'], unique=False)
    op.create_table('run_arms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('arm_name', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_run_arms_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_arms')),
    sa.UniqueConstraint('run_id', 'arm_name', name='uq_run_arms_run_arm')
    )
    op.create_index(op.f('ix_run_arms_run_id'), 'run_arms', ['run_id'], unique=False)
    op.create_table('judgments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rollout_id', sa.Integer(), nullable=False),
    sa.Column('judge_version', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('flags_json', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rollout_id'], ['rollouts.id'], name=op.f('fk_judgments_rollout_id_rollouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_judgments'))
    )
    op.create_index(op.f('ix_judgments_rollout_id'), 'judgments', ['rollout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgments_rollout_id'), table_name='judgments')
    op.drop_table('judgments')
    op.drop_index(op.f('ix_run_arms_run_id'), table_name='run_arms')
    op.drop_table('run_arms')
    op.drop_index(op.f('ix_rollouts_status'), table_name='rollouts')
    op.drop_index(op.f('ix_rollouts_sample_id'), table_name='rollouts')
    op.drop_index(op.f('ix_rollouts_run_id'), table_name='rollouts')
    op.drop_table('rollouts')
    op.drop_index(op.f('ix_metrics_ts'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_run_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_name'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_dlq_entries_run_id'), table_name='dlq_entries')
    op.drop_index(op.f('ix_dlq_entries_next_retry_at'), table_name='dlq_entries')
    op.drop_table('dlq_entries')
    op.drop_index(op.f('ix_artifacts_sha256'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_alert_events_ts'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_run_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_rule'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_experiment_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_samples_dataset_name'), table_name='samples')
    op.drop_table('samples')
    op.drop_table('experiments')
    # ### end Alembic commands ###
