#!/usr/bin/env python3
"""Build notes_en.html — English edition of the "OpenAI math release, explained from zero" deck.

Maintained in parallel with build_notes.py (Chinese); not machine-translated, so edit both when content changes.

Rebuild:  python3 build_notes_en.py  →  notes_en.html
PDF:      Chrome headless print-to-pdf (see README.md)
"""
from pathlib import Path
import figs_en as figs

ROOT = Path(__file__).resolve().parent
CSS = (ROOT / "_notes_base.css").read_text()

EXTRA_CSS = """
  .svg-fig { margin: 24px 0 28px; padding: 18px 16px 12px; background: var(--code-bg);
    border: 1px solid var(--rule); border-radius: 4px; }
  .svg-fig svg { width: 100%; height: auto; display: block; }
  .svg-fig .cap { font-size: 12.5px; color: var(--ink-faint); margin-top: 10px; line-height: 1.5; max-width: none; }
  .ladder { margin: 18px 0 22px; }
  .ladder .rung { display: grid; grid-template-columns: 74px 1fr; gap: 12px; padding: 9px 0;
    border-bottom: 1px solid var(--rule-soft); align-items: start; }
  .ladder .rung:last-child { border-bottom: none; }
  .ladder .lvl { color: var(--accent); font-weight: 600; font-family: ui-monospace, monospace; font-size: 13px; }
  .ladder .body { color: var(--ink-dim); line-height: 1.62; font-size: 15px; }
  .ladder .body strong { color: var(--ink); }
  .claim { margin: 18px 0; padding: 12px 16px; border-left: 3px solid var(--accent); background: var(--code-bg); }
  .claim .label { font-size: 11.5px; text-transform: uppercase; letter-spacing: 0.05em; color: var(--accent); display: block; margin-bottom: 4px; }
  .claim p { margin: 0 0 8px; } .claim p:last-child { margin-bottom: 0; }
  .verdict { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin: 16px 0 22px; }
  @media (max-width: 720px) { .verdict { grid-template-columns: 1fr; } }
  .verdict .panel { border: 1px solid var(--rule-soft); border-radius: 4px; padding: 12px 14px 8px; }
  .verdict .panel h4 { font-family: ui-monospace, monospace; font-size: 12.5px; color: var(--accent); margin: 0 0 8px; }
  .verdict .panel p, .verdict .panel li { font-size: 14px; max-width: none; }
  pre { white-space: pre-wrap; word-break: break-all; }
  .kicker { break-after: avoid; page-break-after: avoid; }
  .tg { font-family: ui-monospace, monospace; font-size: 11px; color: var(--ink-faint); }
  blockquote { margin: 14px 0; padding-left: 14px; border-left: 2px solid var(--rule); color: var(--ink-dim); font-style: italic; }
  .jj h4 { font-size: 14px; margin: 22px 0 8px; color: var(--ink); }
  .jj blockquote { font-style: normal; }
  .jj th { text-transform: none; letter-spacing: 0; }
  .jj table { break-inside: auto; page-break-inside: auto; }
  .jj tr { break-inside: avoid; page-break-inside: avoid; }
  @media print {
    nav.toc { display: none !important; }
    main { max-width: 100%; padding: 24px 32px; }
    .svg-fig, .claim, .verdict, table { break-inside: avoid; page-break-inside: avoid; }
    h2, h3 { break-after: avoid; }
    a { color: var(--ink); text-decoration: none; }
  }
"""

REPO = "https://github.com/openai/math"

TOC = [
    ("scope", "0", "How to use"), ("basics", "1", "Primer"), ("event", "2", "What happened"),
    ("verify", "3", "What Lean guarantees"), ("qrh", "4", "Quasi-Riemann"), ("pi", "5", "Approximating π"),
    ("matmul", "6", "Matrix mult. ω"), ("ugc", "7", "Unique Games"), ("bpl", "8", "L = BPL"),
    ("color", "9", "Coloring the plane"), ("thompson", "10", "Thompson group"), ("ns", "11", "Navier–Stokes"),
    ("vlasov", "12", "Plasma"), ("spin", "13", "Spin glasses"), ("kakeya", "14", "Kakeya & restriction"), ("hodge", "15", "Withdrawals"),
    ("synthesis", "16", "Patterns"), ("ai", "17", "What it means for AI"),
    ("fwd-calib", "18", "Outlook: calibration"), ("fwd-cs", "19", "CS / crypto / quantum"), ("fwd-phys", "20", "Physics / chemistry"),
    ("fwd-bio", "21", "Biology / medicine"), ("fwd-ai", "22", "AI theory & alignment"), ("fwd-soc", "23", "Economy / society"),
    ("fwd-synth", "24", "Big picture & top 10"),
    ("reactions", "25", "Reactions"), ("learn", "26", "Open questions / learn"), ("sources", "27", "Glossary / sources"),
]

BODY = r'''
<header class="masthead">
  <div class="kicker">Learning deck · for AI researchers without a math background</div>
  <h1>OpenAI's 719 AI-generated math papers, explained from zero</h1>
  <p>On 2026-10-06 OpenAI published <strong>722 math manuscripts (372 result families)</strong> generated by an unreleased internal model. Among the claims: the quasi-Riemann hypothesis, the Unique Games Conjecture, matrix-multiplication exponent ω ≤ 9/4, non-amenability of Thompson's group F, and the plane not being 5-colorable — a run of problems open for decades. The next day three manuscripts were withdrawn over a sign error. Mathematicians dubbed it the "Mathocalypse." The goal of this deck: using <strong>only linear algebra, calculus and high-school math</strong>, take 11 representative results far enough that you can judge how big each is, how hard it was, why it matters, and how far it has been verified.</p>
  <p class="meta">First edition 2026-10-08; revised 10-09 (each result now has one from-zero version; new §14 on the Kakeya problem and Fourier restriction; Part II outlook rewritten as §18–§24) · repo snapshot openai/math@fd4aeeb (includes the Oct 7 withdrawals and fixes) · every fact is sourced; [P] = primary material read (paper / repo / Lean source), [R] = secondary reporting, ⚠ = unverified or conflicting · English edition of notes.html (Chinese)</p>
</header>

<section id="scope">
  <div class="kicker">Orientation</div>
  <h2><span class="n">0.</span>What this deck will and won't give you</h2>
  <div class="note">
    <span class="label">You will get</span>
    <p>A "ladder" understanding of each of 11 headline results: start from a toy example you can compute by hand and climb level by level to the real statement; learn how long the problem was stuck and where; see exactly what OpenAI claims, how much the Lean formalization covers, and what human experts have said so far; and what it means for mathematics, for AI, and for AI safety.</p>
  </div>
  <div class="note bug">
    <span class="label">You won't get</span>
    <p>The ability to judge whether any proof is correct. As of 2026-10-09, <strong>none</strong> of these 11 results has a human domain expert publicly saying "I have read and checked it." "Verification" in this deck means two things only: (1) a static review of the Lean source and statements, and (2) a summary of public reactions. Both are labeled with sources and confidence.</p>
  </div>
  <div class="note">
    <span class="label">How the results were chosen</span>
    <p>The deck covers 11 of the 372 result families. Selection criteria: (1) the problem is famous and recognized as hard by experts (those named in first-day coverage and by mathematicians came first); (2) a Lean formalization exists where possible, so the deck can say how far each claim is verified; (3) it can be built up from high-school math and connects to computing or AI; (4) families with a published reasoning summary were preferred. The first edition (10-08) was in practice picked from four fields (number theory, theoretical computer science, combinatorics and group theory, physics and PDE) without a systematic pass over all 17 subject areas. The whole harmonic-analysis cluster (Kakeya, Fourier restriction, Bochner–Riesz, local smoothing, Falconer distance) was missed that way and was added on 10-09 as §14. <strong>Still not covered, though at least comparable by reputation:</strong> Hilbert's tenth problem over ℚ (004), counterexamples to Hadwiger's conjecture (157), a counterexample to Kaplansky's zero-divisor conjecture (196), isomorphism of the free group factors (287), counterexamples to Baum–Connes and Kadison–Kaplansky (285), the Hilbert–Smith conjecture (304), uniform bounds in Hilbert's sixteenth problem (143), and Erdős's reciprocal-sum conjecture with quasipolynomial Szemerédi bounds (159) [speculation: judged from titles only, papers not read]. The full catalogue is in <a href="''' + REPO + '''/blob/main/overview.pdf">overview.pdf</a>.</p>
  </div>
  <h3>0.1 Reading path</h3>
  <p>§1 fills in three basics (what mathematicians do, what an "open problem" is, how to judge how big a result is). §2–§3 cover the event and what Lean actually guarantees — <strong>these two sections determine how you should read every "claim" that follows</strong>. §4–§14 are the 11 results. Each is built up from the most basic concepts, with hand-checkable examples and [Check] exercises, and follows the same structure: <em>bottom line → concepts from zero → what OpenAI claims → how far it is verified → what it would mean if true</em>; read them in any order. §15 is the withdrawal case study, §16–§17 give cross-cutting patterns and implications for AI. <strong>Part II (§18–§24) looks ahead</strong>: if AI solves mathematics at scale, or its other abilities break through too, what happens in computing and cryptography, physics and chemistry, biology and medicine, AI itself, and the economy and governance? §18 calibrates with history and three capability curves; §19–§23 each pick the problems that truly matter in one field and explain whether math is the bottleneck, what AI changes, the deeper impacts and rough timing; §24 gives the big picture, a top 10 and a timeline. §25 collects reactions, §26 lists open questions and a learning path, §27 is the glossary and sources.</p>
  <h3>0.2 Cheat sheet</h3>
  <div class="tbl"><table>
    <thead><tr><th>§</th><th>Result (family no.)</th><th>Open for</th><th>Lean</th><th>One line</th></tr></thead>
    <tbody>
      <tr><td>4</td><td>Quasi-Riemann hypothesis (003)</td><td>~125 yrs</td><td>yes</td><td>ζ has no zeros at all in Re s &gt; 7/8</td></tr>
      <tr><td>5</td><td>Irrationality exponent of π = 2 (017)</td><td>~70 yrs</td><td>yes⚠</td><td>π cannot be approximated "unusually well" by fractions</td></tr>
      <tr><td>6</td><td>Matrix multiplication ω ≤ 9/4 (107)</td><td>57 yrs</td><td>yes</td><td>a drop of 0.12 at once; the previous 12 years gave 0.0017</td></tr>
      <tr><td>7</td><td>Unique Games Conjecture (102)</td><td>24 yrs</td><td>yes</td><td>optimality of many approximation algorithms becomes theorem</td></tr>
      <tr><td>8</td><td>L = RL = BPL (103)</td><td>~30 yrs</td><td>yes</td><td>randomness is useless for small-memory computation</td></tr>
      <tr><td>9</td><td>The plane is not 5-colorable (158)</td><td>76 yrs (last lower-bound step 2018)</td><td>yes</td><td>chromatic number of the plane ∈ {6, 7}</td></tr>
      <tr><td>10</td><td>Thompson's group F non-amenable (248)</td><td>47 yrs</td><td>yes</td><td>famous for "proofs" in both directions later withdrawn</td></tr>
      <tr><td>11</td><td>Navier–Stokes blowup (separate Sept release)</td><td>Millennium Prize problem</td><td>yes</td><td>only the "with forcing" alternative; credit disputed</td></tr>
      <tr><td>12</td><td>Relativistic Vlasov–Maxwell (362)</td><td>40 yrs</td><td>yes</td><td>large-data global smoothness for a plasma model (one species)</td></tr>
      <tr><td>13</td><td>Mézard–Parisi formula (221)</td><td>25 yrs</td><td>yes</td><td>free-energy formula for sparse spin glasses (even-arity case)</td></tr>
      <tr><td>14</td><td>Kakeya: 4D set + 3D maximal (074)</td><td>4D: decades; the 3D set case was only solved in 2025</td><td>no</td><td>every 4D Kakeya set has full dimension 4 (previously about 3.059); the same release also claims the 3D Fourier restriction conjecture (077)</td></tr>
      <tr><td>15</td><td>Hodge-related withdrawals (032 etc.)</td><td>—</td><td>no</td><td>one sign error, three papers withdrawn: the risk of no formalization</td></tr>
    </tbody>
  </table></div>
</section>

<section id="basics">
  <div class="kicker">Fundamentals · primer</div>
  <h2><span class="n">1.</span>What do mathematicians actually do?</h2>
  <p>In one sentence: <strong>they study the structure of abstract objects and establish truths about them by proof</strong>. What separates mathematics from science and engineering is <em>how you know something is right</em>: mathematics by logical proof (once proven, true forever), science by experiment (can be overturned), engineering by "it works and measures well enough."</p>
  <h3>1.1 Four words</h3>
  <div class="tbl"><table>
    <thead><tr><th>Word</th><th>Meaning</th><th>Example from this event</th></tr></thead>
    <tbody>
      <tr><td class="mono">conjecture</td><td>a statement widely believed but unproven</td><td>the Unique Games Conjecture (Khot 2002)</td></tr>
      <tr><td class="mono">theorem</td><td>a statement that has been proven</td><td>the Goemans–Williamson 0.878 algorithm</td></tr>
      <tr><td class="mono">counterexample</td><td>a concrete object showing that a "for all …" conjecture is false</td><td>the 9-dimensional Borsuk counterexample; about 20% of this batch are counterexamples/disproofs</td></tr>
      <tr><td class="mono">formalization</td><td>writing a proof as code a computer can check step by step (here Lean 4)</td><td>about 300/719 top-line results have Lean proofs</td></tr>
    </tbody>
  </table></div>
  <h3>1.2 Two cultures of mathematics</h3>
  <p>In <a href="https://www.dpmms.cam.ac.uk/~wtg10/2cultures.pdf">The Two Cultures of Mathematics</a> (2000), Fields medalist Tim Gowers splits mathematicians into <strong>problem-solvers</strong> (who crack specific hard problems, like Erdős problems) and <strong>theory-builders</strong> (who invent new concepts and frameworks, like "group" or "manifold"). Thurston's <a href="https://arxiv.org/abs/math/9404236">On Proof and Progress in Mathematics</a> (1994) goes further: the point of mathematics is not to produce theorems but to <strong>advance human understanding</strong>. These two essays are the key to this controversy — what AI has broken open at scale is the problem-solving culture, and that is what Tao means by "the end of Math 1.0."</p>
  <h3>1.3 Five questions for judging how big a result is</h3>
  <ol>
    <li><strong>How long was it open, and who tried?</strong> A problem open for 50 years with repeated failures by top experts weighs very differently from one posed two years ago.</li>
    <li><strong>Last step or giant leap?</strong> Moving ω from 2.3713 to 2.3711 is the former; to 2.25 is the latter.</li>
    <li><strong>How much does it unlock?</strong> If UGC holds, hundreds of "if UGC then …" papers become theorems at once.</li>
    <li><strong>Is the method new?</strong> New methods often matter more than the result, because they can be reused.</li>
    <li><strong>Who chose the problem, and how many attempts failed?</strong> The most overlooked question in this event; see §2.3 and §16.</li>
  </ol>
</section>

<section id="event">
  <div class="kicker">The event · timeline and numbers</div>
  <h2><span class="n">2.</span>What happened</h2>
  <div class="tbl"><table>
    <thead><tr><th>Date</th><th>Event</th></tr></thead>
    <tbody>
      <tr><td class="mono">2025-07</td><td>An OpenAI experimental model and Google DeepMind's Gemini Deep Think reach gold-medal scores at IMO 2025 (35/42) — competition problems with known answers fall. <span class="tg">[R]</span></td></tr>
      <tr><td class="mono">2026-09-08</td><td>OpenAI announces that ~10,000 agents over 88 hours proved finite-time blowup "with forcing" for 3D Navier–Stokes (166 pages + Lean), sparking a credit dispute (§11). <span class="tg">[P][R]</span></td></tr>
      <tr><td class="mono">late 2026-09</td><td>The Advisory Group on Mathematics and AI hosted by the Institute for Advanced Study (members include Terence Tao) publishes recommendations for releasing AI-generated mathematics. <span class="tg">[R]</span></td></tr>
      <tr><td class="mono"><strong>2026-10-06</strong></td><td><a href="''' + REPO + '''">openai/math</a> released: 722 manuscripts / 372 result families, Apache-2.0, with a Lean library and 10 abridged reasoning summaries. <span class="tg">[P]</span></td></tr>
      <tr><td class="mono">2026-10-07</td><td>3 manuscripts withdrawn (one sign error, cascading), 14 repaired, 13 re-cited, 6 new formalizations → <strong>719 manuscripts</strong>, "300/719 ≈ 42% of top-line results formalized." A statement from the Association for Human Mathematics (AHM) is reposted on Tao's blog; Scott Aaronson posts <a href="https://scottaaronson.blog/?p=10169">"The Mathocalypse"</a>. <span class="tg">[P][R]</span></td></tr>
      <tr><td class="mono">2026-10-08</td><td>Tao's blog runs a guest post by Lozano-Robledo, <a href="https://terrytao.wordpress.com/2026/10/08/what-should-we-tell-our-students/">What should we tell our students?</a> <span class="tg">[P]</span></td></tr>
    </tbody>
  </table></div>
  <h3>2.1 How the results were produced</h3>
  <p>From the README <span class="tg">[P]</span>: "The vast majority of results were obtained with the same procedure using an unreleased internal OpenAI model. On average, each result used three hours of ChatGPT Pro thinking compute… the model was posed approximately 4,000 problems… requiring an appropriate level of significance led to the catalog." In short: <strong>~4,000 open problems → filtered for significance → 372 families</strong>. An OpenAI spokesperson told Scientific American that almost everything came from "a single prompt handed to a single AI agent" <span class="tg">[R]</span>; MIT's Andrew Sutherland responded that until the model can be replicated, "one-shotting" claims should be treated as unverified — "We should ask for receipts."</p>
  <p><strong>Exceptions</strong>: the README concedes that the zero-free region for ζ (§4) and the Hodge conjecture for CM abelian varieties (§15) were <em>not</em> produced by the fixed procedure, and that the Re s &gt; 11/12 write-up was human-edited. What exactly differed (more compute? human guidance?) is not disclosed ⚠.</p>
  <h3>2.2 Reconciling the numbers</h3>
  <div class="tbl"><table>
    <thead><tr><th>Claim</th><th>What it actually means</th></tr></thead>
    <tbody>
      <tr><td>"722" vs "719"</td><td>722 at release; 719 after the three Oct 7 withdrawals. Early news used 722.</td></tr>
      <tr><td>"372 families" vs "377"</td><td>The catalog is numbered 001–377 with 045/061/070/123/163 unused: 372 actual families.</td></tr>
      <tr><td>"~42% formalized"</td><td>300 <em>top-line results</em> ÷ 719 <em>manuscripts</em> — numerator and denominator in different units. By family, 242/372 ≈ 65% have a Lean scope document.</td></tr>
      <tr><td>"162 fully + 73 partially formalized"</td><td>Reported by some outlets; source not found ⚠.</td></tr>
    </tbody>
  </table></div>
  {{FIG_FIELDS}}
  <h3>2.3 The one thing to keep in mind: selection effects</h3>
  <p>Epoch AI's <a href="https://arxiv.org/abs/2609.25050">FrontierMath Erdős</a> (2026-09) took 68 Erdős problems <strong>pre-registered</strong> as open and required Lean proofs; GPT-6 Astra solved 2 (≈3%), all other models 0. OpenAI's release is <strong>post-hoc selection</strong>: of ~4,000 problems it kept the "significant" ones and published no failure list. A rough hit rate is ≤ 9% (by family) — but problem difficulty is not comparable. <strong>Both numbers are right; they answer different questions</strong>: the first asks "given an arbitrary open problem, can it solve it?", the second "given 4,000, how many good results can it pick out?"</p>
</section>

<section id="verify">
  <div class="kicker">Verification · before reading any "claim"</div>
  <h2><span class="n">3.</span>What "has a Lean proof" actually guarantees</h2>
  <p>Lean is a proof assistant: you write a theorem and its proof as code, and a small <strong>kernel</strong> checks every inference step. If the kernel has no bugs and only accepted axioms are used, passing the check means "this Lean statement is true." The difference from human refereeing is like the difference between a compiler with a type system and code review — the latter misses things; the former doesn't miss <em>what it checks</em>.</p>
  {{FIG_TRUST}}
  <h3>3.1 Our static audit of the Lean library <span class="tg">[P]</span></h3>
  <div class="tbl"><table>
    <thead><tr><th>Check</th><th>Result</th><th>Meaning</th></tr></thead>
    <tbody>
      <tr><td class="mono">sorry (unfinished proof)</td><td>0</td><td>no "fill in later" steps</td></tr>
      <tr><td class="mono">axiom declarations</td><td>0 (all hits are in comments)</td><td>no smuggled-in axioms</td></tr>
      <tr><td class="mono">native_decide / implemented_by / extern</td><td>0</td><td>no "trust the compiler" backdoors</td></tr>
      <tr><td class="mono">decide +kernel</td><td>≈1.31M lines, 5,848 files</td><td>large finite computations done by the kernel — still trusted, but the proofs are enormous</td></tr>
      <tr><td class="mono">Comparator configs</td><td>416, all allowing only the three standard axioms; only 2 enable the second independent kernel nanoda</td><td>see below</td></tr>
      <tr><td class="mono">lean/patches/</td><td>24 patches to third-party dependencies (not the Lean kernel, not Mathlib), largest ~2 MB</td><td>patches change definitions and proofs in dependencies ⚠</td></tr>
      <tr><td class="mono">dependencies</td><td>30, of which 11 are <code>lana-agents/*</code> repos of unknown origin</td><td>an open point in the trust chain ⚠</td></tr>
      <tr><td class="mono">formalization.yaml</td><td><code>review: status: unchecked</code></td><td>OpenAI's own label: not reviewed</td></tr>
    </tbody>
  </table></div>
  <p class="tg">Scope: lean/OAI/ has 122,458 .lean files, ~26M lines; we only grepped the source and counted configs, without compiling (a full build needs many GB of memory and a Linux sandbox). Independent re-checks: Dave Goldblatt ran the ζ 7/8 proof through Comparator and the nanoda kernel (~63 minutes) <a href="https://github.com/davegoldblatt/openai-zeta-proof-check">[repo]</a>; a third party reviewed the statement of the 9/4 matrix-multiplication theorem <a href="https://github.com/erenciracioglu-dotcom/openai-math-9-4-lean-check">[repo]</a>.</p>
  <h3>3.2 Comparator: what it guards against, and what it doesn't</h3>
  <p>The Lean FRO's <a href="https://github.com/leanprover/comparator">Comparator</a> takes a "challenge file" (only the theorem statement, with <code>sorry</code> as the proof, importing only trusted libraries such as Mathlib) and a "solution module": the theorem proven in the solution must be <strong>the same type</strong> as the challenge statement, using only allowed axioms. It guards against swapping the statement, changing definitions or adding axioms inside the proof. It does <strong>not</strong> guard against the challenge statement itself failing to say what the paper claims — and the challenge files were written by OpenAI (its agents). That is why the "verification status" of each section below focuses on <strong>reading the statement line by line</strong>.</p>
  <div class="note bug">
    <span class="label">A live counterexample</span>
    <p>A footnote in OpenAI's plane-coloring paper mentions a May 2026 manuscript that claimed the chromatic number of the plane is 7 with a "formalized theorem" — but that theorem <strong>took a false density bound as a hypothesis</strong>. The formalization was fine; the proven statement was the problem. <span class="tg">[P, as reported in the OpenAI paper; original not read ⚠]</span> This is the same kind of problem as specification gaming in AI: the system perfectly satisfies the written spec, but the spec is not what you wanted.</p>
  </div>
</section>

{{RESULT:qrh}}

{{RESULT:pi}}

{{RESULT:matmul}}

{{RESULT:ugc}}

{{RESULT:bpl}}

{{RESULT:color}}

{{RESULT:thompson}}

{{RESULT:ns}}

{{RESULT:vlasov}}

{{RESULT:spin}}

{{RESULT:kakeya}}
<section id="hodge">
  <div class="kicker">Cautionary case · family 032 and the Oct 7 withdrawals</div>
  <h2><span class="n">15.</span>One sign error, three papers withdrawn: the risk of no formalization</h2>
  <p><strong>The Hodge conjecture</strong> (a Millennium Prize problem), minimally: on a smooth projective complex algebraic variety some "topological holes" can be "filled" by subvarieties defined by algebraic equations; the conjecture says every hole satisfying a certain linear-algebra condition can be filled this way. The case p = 1 has been known since 1924 (Lefschetz).</p>
  <p>OpenAI claims the rational Hodge conjecture for all <strong>complex-multiplication (CM) abelian varieties</strong> (53 pages) — a special class, not the Millennium problem itself; like the ζ zero-free region it was <strong>not</strong> produced by the fixed procedure, and it has <strong>no Lean</strong>. <span class="tg">[P]</span></p>
  {{FIG_HODGE}}
  <h3>15.1 What happened <span class="tg">[P]</span></h3>
  <p>history.md (10-07): "In 'Algebraicity of Weil classes on split abelian eightfolds' a sign error invalidates a stabilization-trace cancellation argument and the construction used by two dependent papers." A sign that should have been −1 was taken as +1; a signed count went from the claimed 0 to −2m ≠ 0, so the hypothesis of a key theorem failed, and two dependent K3-surface papers were withdrawn with it. The CM paper does not cite the withdrawn paper and is not on this chain.</p>
  <h3>15.2 Three lessons</h3>
  <ol>
    <li><strong>Unformalized ≈ unverified</strong>: only ~42% of top-line results have Lean. This error was a single sign — missed by human eyes and the model's self-checks, and Lean would certainly have caught it.</li>
    <li><strong>Errors propagate through the dependency graph</strong>: one lemma fails, three papers fall, 13 downstream papers need new citations — the same structure as error compounding in long agent reasoning chains.</li>
    <li><strong>Title drift</strong>: family 032 was first titled "Hodge and Kuga–Satake results for all projective K3 surfaces" and only downgraded to the CM version after the withdrawals. When reading bulk AI output, trust the latest commit and history.md, not launch-day news.</li>
  </ol>
</section>

<section id="synthesis">
  <div class="kicker">Synthesis · cross-cutting view</div>
  <h2><span class="n">16.</span>The 11 results side by side</h2>
  <div class="tbl"><table>
    <thead><tr><th>Result</th><th>Previous state</th><th>Claimed jump</th><th>Statement faithful?</th><th>Confirmed by human experts</th></tr></thead>
    <tbody>
      <tr><td>Quasi-RH 7/8</td><td>no fixed-width zero-free strip at all</td><td>qualitative</td><td>yes (standard Mathlib definitions)</td><td>none</td></tr>
      <tr><td>μ(π) = 2</td><td>7.103</td><td>straight to the end</td><td>yes (not in yaml ⚠)</td><td>none</td></tr>
      <tr><td>ω ≤ 9/4</td><td>2.371177</td><td>−0.12, past a known barrier</td><td>yes</td><td>none</td></tr>
      <tr><td>UGC</td><td>"half" (2-to-2, 2018)</td><td>complete</td><td>yes (stronger form)</td><td>none</td></tr>
      <tr><td>L = BPL</td><td>near L^(3/2) for 25 years</td><td>complete</td><td>yes (definitions locked)</td><td>none</td></tr>
      <tr><td>Plane χ ≥ 6</td><td>χ ≥ 5 (2018)</td><td>+1, new method</td><td>yes (two-line statement)</td><td>none</td></tr>
      <tr><td>Thompson F</td><td>wrong proofs in both directions</td><td>resolved</td><td>yes</td><td>none</td></tr>
      <tr><td>NS blowup</td><td>forced Euler precursors</td><td>alternatives (C)/(D)</td><td>structure matches</td><td>Clay has not accepted; disputed</td></tr>
      <tr><td>Vlasov–Maxwell</td><td>40 years of restricted results</td><td>complete, one species</td><td>yes</td><td>none</td></tr>
      <tr><td>Mézard–Parisi</td><td>upper bound only</td><td>equality, even-arity class</td><td>yes (narrower than title)</td><td>none</td></tr>
      <tr><td>4D Kakeya / 3D maximal</td><td>4D dimension bound about 3.059; the 3D set case was only solved in 2025</td><td>straight to 4; a stronger 3D version</td><td>cannot be checked (no Lean)</td><td>none</td></tr>
    </tbody>
  </table></div>
  <h3>16.1 Five patterns</h3>
  <ol>
    <li><strong>Short statements, long proofs</strong>: plane coloring has a two-line statement and a 30k-line proof; quasi-RH a one-line statement and a 487k-line proof. This is the ideal "humans review statements, machines check proofs" split — and it makes human reviewing bandwidth the new bottleneck.</li>
    <li><strong>Unusually short papers</strong>: 13 pages for 9/4 matrix multiplication and for Thompson's group. Either the methods really are surprisingly lean, or much of the detail lives in Lean rather than in prose for humans — Gómez-Serrano said the NS paper is "not written for humans."</li>
    <li><strong>Borrowed tools across fields</strong>: Thompson's group via Lipschitz maps from infinite-dimensional geometry; plane coloring via ergodic theory; matrix multiplication via the asymptotic spectrum rather than the dominant laser method of 40 years. This may be a real AI advantage: no human-expert "field inertia."</li>
    <li><strong>The gap between "satisfying the statement" and "answering the real question"</strong>: NS with freely chosen forcing; 376 putting computation in the forcing; the plane-coloring footnote about a formalized false hypothesis; Mézard–Parisi covering only even arity. Each is "spec vs intent."</li>
    <li><strong>Selection effects</strong>: results picked from 4,000 problems vs 3% on pre-registered problems (§2.3). Until OpenAI publishes its failure list, "what is this model's real ability on open problems?" cannot be answered.</li>
  </ol>
</section>

<section id="ai">
  <div class="kicker">AI and AI safety perspective</div>
  <h2><span class="n">17.</span>What this means for AI</h2>
  <h3>17.1 Better at math ≠ smarter across the board — but a leading indicator</h3>
  <p>Mathematics has a unique advantage for AI: <strong>answers can be machine-checked</strong> (Lean), which lets reinforcement learning iterate massively — try, get feedback, improve. Chollet's question goes to the heart of it: does progress in these "verifiable domains" transfer to unverifiable ones? A reasonable reading: <strong>any intellectual work that can be automatically checked will fall at a similar pace next</strong>; mathematics is just the first.</p>
  <h3>17.2 The trust bottleneck moves from "proof" to "specification"</h3>
  <p>Once there is a Lean proof, the question shifts from "is the proof right?" to "is the statement encoded right?" This is isomorphic to a core problem in alignment research: a system can perfectly optimize the objective you wrote down, and what you wrote down may not be what you want. The line-by-line reading of Lean statements done throughout this deck is a form of <strong>spec review</strong> — an increasingly important and scarce human job.</p>
  <h3>17.3 Knowledge that can be verified but not understood</h3>
  <p>In the words of the IAS advisory group: <em>"It is now the case that AI can output mathematical arguments in situations without the human who prompted it being able to understand the arguments, verify them, or take responsibility for them."</em> <span class="tg">[R]</span> Mathematics is where this situation appears first and most cleanly (because verification is perfect). Generalized to science, humans may move from "understanders" to "checkers." Tao's Math 2.0 — putting exposition, community building and opening new directions on a par with problem-solving — is at bottom an answer to "what do humans do in this new division of labor?"</p>
  <h3>17.4 Two sides for safety research</h3>
  <div class="verdict">
    <div class="panel"><h4>Good news</h4><ul>
      <li><strong>Verifying is easier than discovering</strong>: if future AI can give formal proofs about its own behavior ("this action will not do X"), humans need not understand all of its capabilities, only check the proofs — the core idea behind the Guaranteed Safe AI agenda, which becomes more feasible as mathematical AI improves.</li>
      <li>This Lean library is itself the first real sample of "large-scale AI output + machine verification," and its failure modes can be studied.</li></ul></div>
    <div class="panel"><h4>Bad news</h4><ul>
      <li>The hardest parts of alignment ("what does this AI really want?", "is the outcome good for humans?") cannot be written in Lean. Verifiable domains racing ahead while unverifiable ones lag is itself a risk.</li>
      <li>The verifiable parts of AI R&amp;D (kernel optimization, proofs, benchmarks) will be the first to be automated at scale — the "AI improves AI" loop is most likely to start there.</li></ul></div>
  </div>
  <h3>17.5 Governance: a precedent of unilateral dumping</h3>
  <p>The community had begun forming norms through the IAS advisory group (disclose model name, prompts, reasoning chains, compute time and cost, how problems were chosen, failure rates on comparable problems). OpenAI followed some of them, then released 700+ papers at once. AHM's phrase "a demonstration of power" is pointed, but it names a structural problem: <strong>a frontier company unilaterally decides how a capability enters the public domain, and the affected community can only react afterwards</strong>.</p>
</section>

{{PART2:18}}
{{PART2:19}}
{{PART2:20}}
{{PART2:21}}
{{PART2:22}}
{{PART2:23}}
{{PART2:24}}

<section id="reactions">
  <div class="kicker">Reactions · in their words</div>
  <h2><span class="n">25.</span>What people said</h2>
  <div class="tbl"><table>
    <thead><tr><th>Who</th><th>Quote</th><th>Source</th></tr></thead>
    <tbody>
      <tr><td>Levent Alpöge (Anthropic)</td><td>"It's obviously the most significant moment in mathematical history." (later adding there would be "sad stories" of people being scooped)</td><td>X <span class="tg">[R]</span></td></tr>
      <tr><td>Terence Tao</td><td>"Problems are being solved autonomously by AI prompters who have no interest in the broader field itself"; proposes Math 1.0 → 2.0</td><td>Fortune <span class="tg">[R]</span></td></tr>
      <tr><td>Dan Litt (Toronto)</td><td>"My view is that this is great for mathematics," while worrying that an "AI has solved math" perception could discourage young people</td><td>Fortune <span class="tg">[R]</span></td></tr>
      <tr><td>Tristan Buckmaster (NYU)</td><td>"There's likely to be a bunch of results where they take someone's work and then take it to completion"</td><td>Fortune <span class="tg">[R]</span></td></tr>
      <tr><td>Scott Aaronson</td><td>Post "The Mathocalypse"; on L = BPL: "its truth was never in serious doubt"</td><td><a href="https://scottaaronson.blog/?p=10169">blog</a> <span class="tg">[R]</span></td></tr>
      <tr><td>Lance Fortnow</td><td>"if they hold up, we've seen more progress in TCS in the last 24 hours than in the previous three decades combined"</td><td>Computational Complexity blog <span class="tg">[R]</span></td></tr>
      <tr><td>Mark Braverman</td><td>"Math by press release is not that healthy for math."</td><td>Quanta <span class="tg">[R]</span></td></tr>
      <tr><td>François Chollet</td><td>Asks whether gains in RLVR-friendly domains generalize, or whether non-verifiable domains stay bottlenecked on human data</td><td>X (paraphrase) <span class="tg">[R]</span></td></tr>
      <tr><td>AHM</td><td>"Releasing over 700 files at once is not a demonstration of scholarship, but a demonstration of power."; urges mathematicians to stop working with OpenAI</td><td><a href="https://terrytao.wordpress.com/2026/10/07/ahm-statement-on-openais-october-6-release-of-mathematical-documents/">reposted on Tao's blog</a> (Tao notes he does not endorse it) <span class="tg">[P]</span></td></tr>
      <tr><td>Álvaro Lozano-Robledo</td><td>"Keep calm and carry on studying math."; LLMs "may work within the confines of the convex hull of ideas that are currently available in the literature"</td><td><a href="https://terrytao.wordpress.com/2026/10/08/what-should-we-tell-our-students/">guest post on Tao's blog</a> <span class="tg">[P]</span></td></tr>
      <tr><td>Andrew Sutherland (MIT)</td><td>"We should ask for receipts."</td><td>via Scientific American <span class="tg">[R]</span></td></tr>
    </tbody>
  </table></div>
  <p class="tg">Note: "The Future of Mathematics" on Tao's blog (10-05) is a guest post by Jeremy Avigad, not by Tao; some coverage conflated the two.</p>
</section>

<section id="learn">
  <div class="kicker">Next steps</div>
  <h2><span class="n">26.</span>Open questions and how to keep learning</h2>
  <h3>26.1 What to watch</h3>
  <ol>
    <li>Will OpenAI publish the list of ~4,000 problems and the failures? (This decides whether "what is the real capability?" can be answered.)</li>
    <li>How many errors like the Weil-class paper remain in the ~58% that is unformalized? How will the withdrawal rate evolve?</li>
    <li>Who reviews the faithfulness of the Lean statements? When does <code>review: unchecked</code> change? Who audits the <code>lana-agents</code> dependencies and the large patches?</li>
    <li>When will the first human domain expert give an independent "read and confirmed" verdict on a headline result (quasi-RH, UGC, Thompson F)?</li>
    <li>What priority norms should govern "completing someone else's work" (the Buckmaster episode)?</li>
    <li>Chromatic number of the plane: what does a finite unit-distance graph needing 6 colors look like?</li>
  </ol>
  <h3>26.2 Learning path (starting from linear algebra + calculus)</h3>
  <div class="tbl"><table>
    <thead><tr><th>Stage</th><th>Material</th><th>Why</th></tr></thead>
    <tbody>
      <tr><td>1 · What math is</td><td>Gowers, <em>Mathematics: A Very Short Introduction</em></td><td>150 pages by a Fields medalist: abstraction, proof, what "hard" means</td></tr>
      <tr><td>1 · Roots of this debate</td><td>Thurston, <a href="https://arxiv.org/abs/math/9404236">On Proof and Progress in Mathematics</a>; Gowers, <a href="https://www.dpmms.cam.ac.uk/~wtg10/2cultures.pdf">The Two Cultures of Mathematics</a>; Tao, <a href="https://arxiv.org/abs/math/0702396">What is good mathematics?</a></td><td>after these, "Math 1.0 → 2.0" makes complete sense</td></tr>
      <tr><td>2 · Touch a proof</td><td>Natural Number Game (Kevin Buzzard, free online)</td><td>prove commutativity of addition from scratch in Lean — then §3 makes full sense</td></tr>
      <tr><td>2 · Learn proofs systematically</td><td>MIT 6.042 Mathematics for Computer Science (OCW + free textbook)</td><td>designed for CS backgrounds: proof methods, discrete math, probability</td></tr>
      <tr><td>3 · Intuition</td><td>3Blue1Brown: <em>Essence of linear algebra</em>; visualizing the Riemann zeta function</td><td>the figure in §4 is a static version of that episode</td></tr>
      <tr><td>3 · Following the news</td><td>Quanta Magazine (math); <em>The Princeton Companion to Mathematics</em> (as a reference)</td><td>every piece explains why a problem is hard and where people were stuck</td></tr>
      <tr><td>4 · ML-adjacent</td><td>Bubeck, <a href="https://arxiv.org/abs/1405.4980">Convex Optimization: Algorithms and Complexity</a>; Prince, <em>Understanding Deep Learning</em> (free)</td><td>convergence proofs for optimization; intro to deep-learning theory</td></tr>
    </tbody>
  </table></div>
</section>

<section id="sources">
  <div class="kicker">Glossary and sources</div>
  <h2><span class="n">27.</span>Glossary and sources</h2>
  <h3>27.1 Glossary</h3>
  <div class="tbl"><table>
    <thead><tr><th>Term</th><th>In one line</th></tr></thead>
    <tbody>
      <tr><td class="mono">Lean / Mathlib</td><td>a proof assistant / its community math library</td></tr>
      <tr><td class="mono">sorry / axiom</td><td>in Lean: "leave this step empty" / "assume this is true" — both weaken a proof</td></tr>
      <tr><td class="mono">Comparator</td><td>tool checking "the theorem proven = the challenge statement, using only allowed axioms"</td></tr>
      <tr><td class="mono">zero-free region</td><td>a region where ζ or an L-function has no zeros</td></tr>
      <tr><td class="mono">irrationality exponent μ</td><td>how "unusually well" a number can be approximated by fractions</td></tr>
      <tr><td class="mono">ω</td><td>the optimal exponent of matrix multiplication, 2 ≤ ω ≤ 3</td></tr>
      <tr><td class="mono">approximation ratio</td><td>the fraction of the optimum a polynomial-time algorithm guarantees</td></tr>
      <tr><td class="mono">L / RL / BPL</td><td>log-space deterministic / one-sided randomized / two-sided randomized computation</td></tr>
      <tr><td class="mono">amenable</td><td>a group admits a translation-invariant "average"</td></tr>
      <tr><td class="mono">blowup</td><td>a solution of a smooth equation going to infinity in finite time</td></tr>
      <tr><td class="mono">replica symmetry breaking (RSB)</td><td>Parisi's description of the hierarchical state structure of spin glasses</td></tr>
      <tr><td class="mono">galactic algorithm</td><td>asymptotically faster, but only better at astronomical sizes</td></tr>
    </tbody>
  </table></div>
  <h3>27.2 Main sources</h3>
  <p><strong>Primary</strong>: <a href="''' + REPO + '''">openai/math</a> (README, history.md, overview.pdf, CONTENTS.md, lean/, preprints/, reasoning_traces/; snapshot fd4aeeb, 2026-10-08) · <a href="https://github.com/openai/NavierStokesAndEuler">openai/NavierStokesAndEuler</a> · <a href="https://www.claymath.org/wp-content/uploads/2022/06/navierstokes.pdf">Clay NS official statement (Fefferman)</a> · <a href="https://github.com/leanprover/comparator">leanprover/comparator</a> · independent re-checks <a href="https://github.com/davegoldblatt/openai-zeta-proof-check">davegoldblatt/openai-zeta-proof-check</a>, <a href="https://github.com/erenciracioglu-dotcom/openai-math-9-4-lean-check">erenciracioglu-dotcom/openai-math-9-4-lean-check</a> · Epoch <a href="https://arxiv.org/abs/2609.25050">FrontierMath Erdős (arXiv:2609.25050)</a>.</p>
  <p><strong>Coverage and commentary</strong>: <a href="https://fortune.com/2026/10/07/openai-math-controversy-solutions-370-outstanding-challenges-published-criticisms-celebration/">Fortune 10-07</a> · <a href="https://www.nature.com/articles/d41586-026-03196-8">Nature</a> (paywalled, full text not read ⚠) · <a href="https://www.scientificamerican.com/article/openai-unleashes-hundreds-more-math-results-upon-a-field-already-in-shock/">Scientific American</a> · <a href="https://www.quantamagazine.org/ai-has-solved-one-of-maths-1-million-millennium-prize-problems-20260908/">Quanta 09-08</a> · <a href="https://www.quantamagazine.org/as-ai-closed-in-on-unique-games-proof-researchers-raced-to-beat-the-machines-20261007/">Quanta 10-07</a> · <a href="https://www.npr.org/2026/09/22/nx-s1-5968588/openai-navier-stokes-problem-mathematicians-learn-little">NPR 09-22</a> · <a href="https://scottaaronson.blog/?p=10169">Aaronson</a> · <a href="https://gilkalai.wordpress.com/2026/10/07/updates-sharing-ai-progress-on-mathematics-amazing-and-my-lecture-plans/">Kalai</a> · <a href="https://terrytao.wordpress.com/">Tao's blog</a> · <a href="https://www.latent.space/p/ainews-quasi-riemann-hypothesis-openai">Latent Space</a>.</p>
  <p><strong>Classic references</strong>: Strassen 1969; Coppersmith–Winograd 1990; Alman et al. <a href="https://arxiv.org/abs/2404.16349">arXiv:2404.16349</a>; Ambainis–Filmus–Le Gall <a href="https://arxiv.org/abs/1411.5414">arXiv:1411.5414</a>; Goemans–Williamson 1995; Khot 2002; KKMO 2007; Raghavendra 2008; Khot–Minzer–Safra 2018; Nisan 1992; Saks–Zhou 1999; Reingold 2008; Roth 1955; Zeilberger–Zudilin <a href="https://arxiv.org/abs/1912.06345">arXiv:1912.06345</a>; Meiburg <a href="https://arxiv.org/abs/2208.13356">arXiv:2208.13356</a>; Guth–Maynard <a href="https://arxiv.org/abs/2405.20552">arXiv:2405.20552</a>; de Grey <a href="https://arxiv.org/abs/1804.02385">arXiv:1804.02385</a>; Moore <a href="https://arxiv.org/abs/1102.0747">arXiv:1102.0747</a>; Tao 2016 <a href="https://arxiv.org/abs/1402.0290">arXiv:1402.0290</a>; Glassey–Strauss 1986; Parisi 1979; Talagrand 2006; Mézard–Parisi 2001; Ding–Sly–Sun 2015.</p>
</section>
'''

FIGS = {
    "{{FIG_FIELDS}}": figs.svg_fields(), "{{FIG_TRUST}}": figs.svg_trust(), "{{FIG_ZETA}}": figs.svg_zeta(),
    "{{FIG_FLINT}}": figs.svg_flint(), "{{FIG_OMEGA}}": figs.svg_omega(), "{{FIG_MAXCUT}}": figs.svg_maxcut(),
    "{{FIG_MOSER}}": figs.svg_moser(), "{{FIG_THOMPSON}}": figs.svg_thompson(), "{{FIG_BLOWUP}}": figs.svg_blowup(),
    "{{FIG_HARMONIC}}": figs.svg_harmonic(), "{{FIG_SPIN}}": figs.svg_spin(), "{{FIG_HODGE}}": figs.svg_hodge(),
    "{{FIG_METR}}": figs.svg_metr(figs.METR_EN), "{{FIG_OPEN}}": figs.svg_openprob(figs.OPEN_EN),
}
import md2html

JJ_DIR = ROOT / "精讲" / "en"


RESULT_KICKERS = {
    "qrh": "Number theory · family 003",
    "pi": "Number theory · family 017 (+ 005)",
    "matmul": "Theoretical CS · family 107",
    "ugc": "Theoretical CS · family 102",
    "bpl": "Theoretical CS · family 103 (+ 109)",
    "color": "Combinatorics · family 158 (+ 156)",
    "thompson": "Group theory · family 248",
    "ns": "PDE · separate September release (+ family 376)",
    "vlasov": "Mathematical physics · family 362",
    "spin": "Probability and statistical mechanics · family 221",
    "kakeya": "Harmonic analysis · family 074 (+ 077)",
}
RESULT_ORDER = ['qrh', 'pi', 'matmul', 'ugc', 'bpl', 'color', 'thompson', 'ns', 'vlasov', 'spin', 'kakeya']


def result_html(sid):
    """One result section (§4–§14), rendered from its chapter Markdown file."""
    k = RESULT_ORDER.index(sid) + 1
    files = sorted(JJ_DIR.glob(f"{k:02d}_*.md"))
    assert len(files) == 1, f"result {sid}: expected exactly one chapter file, got {files}"
    md = files[0].read_text()
    first, _, rest = md.partition("\n")
    assert first.startswith("# "), files[0]
    return f'''<section id="{sid}" class="jj">
  <div class="kicker">{RESULT_KICKERS[sid]}</div>
  <h2><span class="n">{3 + k}.</span>{md2html.inline(first[2:].strip())}</h2>
{md2html.blocks(rest, heading_offset=1)}
</section>'''


for _sid in RESULT_ORDER:
    BODY = BODY.replace("{{RESULT:%s}}" % _sid, result_html(_sid))

P2_DIR = ROOT / "前瞻" / "en"
P2_SECTIONS = [('fwd-calib', 18), ('fwd-cs', 19), ('fwd-phys', 20), ('fwd-bio', 21), ('fwd-ai', 22), ('fwd-soc', 23), ('fwd-synth', 24)]
P2_KICKERS = {18: 'Part II · Outlook · calibration', 19: 'Part II · Outlook · computing', 20: 'Part II · Outlook · physics', 21: 'Part II · Outlook · biology', 22: 'Part II · Outlook · AI itself', 23: 'Part II · Outlook · society', 24: 'Part II · Outlook · big picture'}


def part2_html(sec_id, n):
    """One Part II section, rendered from 前瞻/en/NN_*.md."""
    files = sorted(P2_DIR.glob(f"{n}_*.md"))
    assert len(files) == 1, f"Part II §{n}: expected exactly one file, got {files}"
    md = files[0].read_text()
    first, _, rest = md.partition("\n")
    assert first.startswith("# "), files[0]
    return f'''<section id="{sec_id}" class="jj">
  <div class="kicker">{P2_KICKERS[n]}</div>
  <h2><span class="n">{n}.</span>{md2html.inline(first[2:].strip())}</h2>
{md2html.blocks(rest, heading_offset=1)}
</section>'''


for _sec_id, _n in P2_SECTIONS:
    BODY = BODY.replace("{{PART2:%d}}" % _n, part2_html(_sec_id, _n))
import re as _re
while _re.search(r'\^\{([^{}]*)\}', BODY):
    BODY = _re.sub(r'\^\{([^{}]*)\}', r'^(\1)', BODY)
for k, v in FIGS.items():
    assert k in BODY, k
    BODY = BODY.replace(k, v)

toc_html = "\n".join(f'  <a href="#{i}"><span class="num">{n}</span>{t}</a>' for i, n, t in TOC)

HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>OpenAI Math Release, Explained</title>
<style>
""" + CSS + EXTRA_CSS + """
</style>
</head>
<body>
<div class="page">
<nav class="toc">
""" + toc_html + """
</nav>
<main>
""" + BODY + """
</main>
</div>
<script>
(() => {
  const links = [...document.querySelectorAll('nav.toc a')];
  const sections = links.map(a => document.querySelector(a.getAttribute('href'))).filter(Boolean);
  const io = new IntersectionObserver((entries) => {
    entries.forEach(e => {
      if (!e.isIntersecting) return;
      const id = '#' + e.target.id;
      links.forEach(l => l.classList.toggle('active', l.getAttribute('href') === id));
    });
  }, { rootMargin: '-40% 0px -50% 0px', threshold: 0 });
  sections.forEach(s => io.observe(s));
})();
</script>
</body>
</html>
"""

out = ROOT / "notes_en.html"
out.write_text(HTML)
print(f"wrote {out} ({len(HTML)} bytes)")
