#!/usr/bin/env python3
"""Build notes_en.html — English edition of the "OpenAI math release, explained from zero" deck.

Maintained in parallel with build_notes.py (Chinese); not machine-translated, so edit both when content changes.

Rebuild:  python3 build_notes_en.py  →  notes_en.html
PDF:      Chrome headless print-to-pdf (see README.md)
"""
from pathlib import Path
import figs_en as figs

ROOT = Path(__file__).resolve().parent
CSS = (ROOT / "_notes_base.css").read_text()

EXTRA_CSS = """
  .svg-fig { margin: 24px 0 28px; padding: 18px 16px 12px; background: var(--code-bg);
    border: 1px solid var(--rule); border-radius: 4px; }
  .svg-fig svg { width: 100%; height: auto; display: block; }
  .svg-fig .cap { font-size: 12.5px; color: var(--ink-faint); margin-top: 10px; line-height: 1.5; max-width: none; }
  .ladder { margin: 18px 0 22px; }
  .ladder .rung { display: grid; grid-template-columns: 74px 1fr; gap: 12px; padding: 9px 0;
    border-bottom: 1px solid var(--rule-soft); align-items: start; }
  .ladder .rung:last-child { border-bottom: none; }
  .ladder .lvl { color: var(--accent); font-weight: 600; font-family: ui-monospace, monospace; font-size: 13px; }
  .ladder .body { color: var(--ink-dim); line-height: 1.62; font-size: 15px; }
  .ladder .body strong { color: var(--ink); }
  .claim { margin: 18px 0; padding: 12px 16px; border-left: 3px solid var(--accent); background: var(--code-bg); }
  .claim .label { font-size: 11.5px; text-transform: uppercase; letter-spacing: 0.05em; color: var(--accent); display: block; margin-bottom: 4px; }
  .claim p { margin: 0 0 8px; } .claim p:last-child { margin-bottom: 0; }
  .verdict { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin: 16px 0 22px; }
  @media (max-width: 720px) { .verdict { grid-template-columns: 1fr; } }
  .verdict .panel { border: 1px solid var(--rule-soft); border-radius: 4px; padding: 12px 14px 8px; }
  .verdict .panel h4 { font-family: ui-monospace, monospace; font-size: 12.5px; color: var(--accent); margin: 0 0 8px; }
  .verdict .panel p, .verdict .panel li { font-size: 14px; max-width: none; }
  pre { white-space: pre-wrap; word-break: break-all; }
  .kicker { break-after: avoid; page-break-after: avoid; }
  .tg { font-family: ui-monospace, monospace; font-size: 11px; color: var(--ink-faint); }
  blockquote { margin: 14px 0; padding-left: 14px; border-left: 2px solid var(--rule); color: var(--ink-dim); font-style: italic; }
  @media print {
    nav.toc { display: none !important; }
    main { max-width: 100%; padding: 24px 32px; }
    .svg-fig, .claim, .verdict, table { break-inside: avoid; page-break-inside: avoid; }
    h2, h3 { break-after: avoid; }
    a { color: var(--ink); text-decoration: none; }
  }
"""

REPO = "https://github.com/openai/math"

TOC = [
    ("scope", "0", "How to use"), ("basics", "1", "Primer"), ("event", "2", "What happened"),
    ("verify", "3", "What Lean guarantees"), ("qrh", "4", "Quasi-Riemann"), ("pi", "5", "Approximating π"),
    ("matmul", "6", "Matrix mult. ω"), ("ugc", "7", "Unique Games"), ("bpl", "8", "L = BPL"),
    ("color", "9", "Coloring the plane"), ("thompson", "10", "Thompson group"), ("ns", "11", "Navier–Stokes"),
    ("vlasov", "12", "Plasma"), ("spin", "13", "Spin glasses"), ("hodge", "14", "Withdrawals"),
    ("synthesis", "15", "Patterns"), ("ai", "16", "What it means for AI"), ("reactions", "17", "Reactions"),
    ("learn", "18", "Open questions / learn"), ("sources", "19", "Glossary / sources"),
]

BODY = r'''
<header class="masthead">
  <div class="kicker">Learning deck · for AI researchers without a math background</div>
  <h1>OpenAI's 719 AI-generated math papers, explained from zero</h1>
  <p>On 2026-10-06 OpenAI published <strong>722 math manuscripts (372 result families)</strong> generated by an unreleased internal model. Among the claims: the quasi-Riemann hypothesis, the Unique Games Conjecture, matrix-multiplication exponent ω ≤ 9/4, non-amenability of Thompson's group F, and the plane not being 5-colorable — a run of problems open for decades. The next day three manuscripts were withdrawn over a sign error. Mathematicians dubbed it the "Mathocalypse." The goal of this deck: using <strong>only linear algebra, calculus and high-school math</strong>, take 10 representative results far enough that you can judge how big each is, how hard it was, why it matters, and how far it has been verified.</p>
  <p class="meta">First edition 2026-10-08 · repo snapshot openai/math@fd4aeeb (includes the Oct 7 withdrawals and fixes) · every fact is sourced; [P] = primary material read (paper / repo / Lean source), [R] = secondary reporting, ⚠ = unverified or conflicting · English edition of notes.html (Chinese)</p>
</header>

<section id="scope">
  <div class="kicker">Orientation</div>
  <h2><span class="n">0.</span>What this deck will and won't give you</h2>
  <div class="note">
    <span class="label">You will get</span>
    <p>A "ladder" understanding of each of 10 headline results: start from a toy example you can compute by hand and climb level by level to the real statement; learn how long the problem was stuck and where; see exactly what OpenAI claims, how much the Lean formalization covers, and what human experts have said so far; and what it means for mathematics, for AI, and for AI safety.</p>
  </div>
  <div class="note bug">
    <span class="label">You won't get</span>
    <p>The ability to judge whether any proof is correct. As of 2026-10-08, <strong>none</strong> of these 10 results has a human domain expert publicly saying "I have read and checked it." "Verification" in this deck means two things only: (1) a static review of the Lean source and statements, and (2) a summary of public reactions. Both are labeled with sources and confidence.</p>
  </div>
  <h3>0.1 Reading path</h3>
  <p>§1 fills in three basics (what mathematicians do, what an "open problem" is, how to judge how big a result is). §2–§3 cover the event and what Lean actually guarantees — <strong>these two sections determine how you should read every "claim" that follows</strong>. §4–§14 are the 10 results, each with the same structure: <em>ladder → problem → why it was hard → what OpenAI claims → verification status → if true</em>; read them in any order. §15–§16 give cross-cutting patterns and implications for AI, §17 collects reactions, §18 lists open questions and a learning path, §19 is the glossary and sources.</p>
  <h3>0.2 Cheat sheet</h3>
  <div class="tbl"><table>
    <thead><tr><th>§</th><th>Result (family no.)</th><th>Open for</th><th>Lean</th><th>One line</th></tr></thead>
    <tbody>
      <tr><td>4</td><td>Quasi-Riemann hypothesis (003)</td><td>~125 yrs</td><td>yes</td><td>ζ has no zeros at all in Re s &gt; 7/8</td></tr>
      <tr><td>5</td><td>Irrationality exponent of π = 2 (017)</td><td>~70 yrs</td><td>yes⚠</td><td>π cannot be approximated "unusually well" by fractions</td></tr>
      <tr><td>6</td><td>Matrix multiplication ω ≤ 9/4 (107)</td><td>57 yrs</td><td>yes</td><td>a drop of 0.12 at once; the previous 12 years gave 0.0017</td></tr>
      <tr><td>7</td><td>Unique Games Conjecture (102)</td><td>24 yrs</td><td>yes</td><td>optimality of many approximation algorithms becomes theorem</td></tr>
      <tr><td>8</td><td>L = RL = BPL (103)</td><td>~30 yrs</td><td>yes</td><td>randomness is useless for small-memory computation</td></tr>
      <tr><td>9</td><td>The plane is not 5-colorable (158)</td><td>76 yrs (last lower-bound step 2018)</td><td>yes</td><td>chromatic number of the plane ∈ {6, 7}</td></tr>
      <tr><td>10</td><td>Thompson's group F non-amenable (248)</td><td>47 yrs</td><td>yes</td><td>famous for "proofs" in both directions later withdrawn</td></tr>
      <tr><td>11</td><td>Navier–Stokes blowup (separate Sept release)</td><td>Millennium Prize problem</td><td>yes</td><td>only the "with forcing" alternative; credit disputed</td></tr>
      <tr><td>12</td><td>Relativistic Vlasov–Maxwell (362)</td><td>40 yrs</td><td>yes</td><td>large-data global smoothness for a plasma model (one species)</td></tr>
      <tr><td>13</td><td>Mézard–Parisi formula (221)</td><td>25 yrs</td><td>yes</td><td>free-energy formula for sparse spin glasses (even-arity case)</td></tr>
      <tr><td>14</td><td>Hodge-related withdrawals (032 etc.)</td><td>—</td><td>no</td><td>one sign error, three papers withdrawn: the risk of no formalization</td></tr>
    </tbody>
  </table></div>
</section>

<section id="basics">
  <div class="kicker">Fundamentals · primer</div>
  <h2><span class="n">1.</span>What do mathematicians actually do?</h2>
  <p>In one sentence: <strong>they study the structure of abstract objects and establish truths about them by proof</strong>. What separates mathematics from science and engineering is <em>how you know something is right</em>: mathematics by logical proof (once proven, true forever), science by experiment (can be overturned), engineering by "it works and measures well enough."</p>
  <h3>1.1 Four words</h3>
  <div class="tbl"><table>
    <thead><tr><th>Word</th><th>Meaning</th><th>Example from this event</th></tr></thead>
    <tbody>
      <tr><td class="mono">conjecture</td><td>a statement widely believed but unproven</td><td>the Unique Games Conjecture (Khot 2002)</td></tr>
      <tr><td class="mono">theorem</td><td>a statement that has been proven</td><td>the Goemans–Williamson 0.878 algorithm</td></tr>
      <tr><td class="mono">counterexample</td><td>a concrete object showing that a "for all …" conjecture is false</td><td>the 9-dimensional Borsuk counterexample; about 20% of this batch are counterexamples/disproofs</td></tr>
      <tr><td class="mono">formalization</td><td>writing a proof as code a computer can check step by step (here Lean 4)</td><td>about 300/719 top-line results have Lean proofs</td></tr>
    </tbody>
  </table></div>
  <h3>1.2 Two cultures of mathematics</h3>
  <p>In <a href="https://www.dpmms.cam.ac.uk/~wtg10/2cultures.pdf">The Two Cultures of Mathematics</a> (2000), Fields medalist Tim Gowers splits mathematicians into <strong>problem-solvers</strong> (who crack specific hard problems, like Erdős problems) and <strong>theory-builders</strong> (who invent new concepts and frameworks, like "group" or "manifold"). Thurston's <a href="https://arxiv.org/abs/math/9404236">On Proof and Progress in Mathematics</a> (1994) goes further: the point of mathematics is not to produce theorems but to <strong>advance human understanding</strong>. These two essays are the key to this controversy — what AI has broken open at scale is the problem-solving culture, and that is what Tao means by "the end of Math 1.0."</p>
  <h3>1.3 Five questions for judging how big a result is</h3>
  <ol>
    <li><strong>How long was it open, and who tried?</strong> A problem open for 50 years with repeated failures by top experts weighs very differently from one posed two years ago.</li>
    <li><strong>Last step or giant leap?</strong> Moving ω from 2.3713 to 2.3711 is the former; to 2.25 is the latter.</li>
    <li><strong>How much does it unlock?</strong> If UGC holds, hundreds of "if UGC then …" papers become theorems at once.</li>
    <li><strong>Is the method new?</strong> New methods often matter more than the result, because they can be reused.</li>
    <li><strong>Who chose the problem, and how many attempts failed?</strong> The most overlooked question in this event; see §2.3 and §15.</li>
  </ol>
</section>

<section id="event">
  <div class="kicker">The event · timeline and numbers</div>
  <h2><span class="n">2.</span>What happened</h2>
  <div class="tbl"><table>
    <thead><tr><th>Date</th><th>Event</th></tr></thead>
    <tbody>
      <tr><td class="mono">2025-07</td><td>An OpenAI experimental model and Google DeepMind's Gemini Deep Think reach gold-medal scores at IMO 2025 (35/42) — competition problems with known answers fall. <span class="tg">[R]</span></td></tr>
      <tr><td class="mono">2026-09-08</td><td>OpenAI announces that ~10,000 agents over 88 hours proved finite-time blowup "with forcing" for 3D Navier–Stokes (166 pages + Lean), sparking a credit dispute (§11). <span class="tg">[P][R]</span></td></tr>
      <tr><td class="mono">late 2026-09</td><td>The Advisory Group on Mathematics and AI hosted by the Institute for Advanced Study (members include Terence Tao) publishes recommendations for releasing AI-generated mathematics. <span class="tg">[R]</span></td></tr>
      <tr><td class="mono"><strong>2026-10-06</strong></td><td><a href="''' + REPO + '''">openai/math</a> released: 722 manuscripts / 372 result families, Apache-2.0, with a Lean library and 10 abridged reasoning summaries. <span class="tg">[P]</span></td></tr>
      <tr><td class="mono">2026-10-07</td><td>3 manuscripts withdrawn (one sign error, cascading), 14 repaired, 13 re-cited, 6 new formalizations → <strong>719 manuscripts</strong>, "300/719 ≈ 42% of top-line results formalized." A statement from the Association for Human Mathematics (AHM) is reposted on Tao's blog; Scott Aaronson posts <a href="https://scottaaronson.blog/?p=10169">"The Mathocalypse"</a>. <span class="tg">[P][R]</span></td></tr>
      <tr><td class="mono">2026-10-08</td><td>Tao's blog runs a guest post by Lozano-Robledo, <a href="https://terrytao.wordpress.com/2026/10/08/what-should-we-tell-our-students/">What should we tell our students?</a> <span class="tg">[P]</span></td></tr>
    </tbody>
  </table></div>
  <h3>2.1 How the results were produced</h3>
  <p>From the README <span class="tg">[P]</span>: "The vast majority of results were obtained with the same procedure using an unreleased internal OpenAI model. On average, each result used three hours of ChatGPT Pro thinking compute… the model was posed approximately 4,000 problems… requiring an appropriate level of significance led to the catalog." In short: <strong>~4,000 open problems → filtered for significance → 372 families</strong>. An OpenAI spokesperson told Scientific American that almost everything came from "a single prompt handed to a single AI agent" <span class="tg">[R]</span>; MIT's Andrew Sutherland responded that until the model can be replicated, "one-shotting" claims should be treated as unverified — "We should ask for receipts."</p>
  <p><strong>Exceptions</strong>: the README concedes that the zero-free region for ζ (§4) and the Hodge conjecture for CM abelian varieties (§14) were <em>not</em> produced by the fixed procedure, and that the Re s &gt; 11/12 write-up was human-edited. What exactly differed (more compute? human guidance?) is not disclosed ⚠.</p>
  <h3>2.2 Reconciling the numbers</h3>
  <div class="tbl"><table>
    <thead><tr><th>Claim</th><th>What it actually means</th></tr></thead>
    <tbody>
      <tr><td>"722" vs "719"</td><td>722 at release; 719 after the three Oct 7 withdrawals. Early news used 722.</td></tr>
      <tr><td>"372 families" vs "377"</td><td>The catalog is numbered 001–377 with 045/061/070/123/163 unused: 372 actual families.</td></tr>
      <tr><td>"~42% formalized"</td><td>300 <em>top-line results</em> ÷ 719 <em>manuscripts</em> — numerator and denominator in different units. By family, 242/372 ≈ 65% have a Lean scope document.</td></tr>
      <tr><td>"162 fully + 73 partially formalized"</td><td>Reported by some outlets; source not found ⚠.</td></tr>
    </tbody>
  </table></div>
  {{FIG_FIELDS}}
  <h3>2.3 The one thing to keep in mind: selection effects</h3>
  <p>Epoch AI's <a href="https://arxiv.org/abs/2609.25050">FrontierMath Erdős</a> (2026-09) took 68 Erdős problems <strong>pre-registered</strong> as open and required Lean proofs; GPT-6 Astra solved 2 (≈3%), all other models 0. OpenAI's release is <strong>post-hoc selection</strong>: of ~4,000 problems it kept the "significant" ones and published no failure list. A rough hit rate is ≤ 9% (by family) — but problem difficulty is not comparable. <strong>Both numbers are right; they answer different questions</strong>: the first asks "given an arbitrary open problem, can it solve it?", the second "given 4,000, how many good results can it pick out?"</p>
</section>

<section id="verify">
  <div class="kicker">Verification · before reading any "claim"</div>
  <h2><span class="n">3.</span>What "has a Lean proof" actually guarantees</h2>
  <p>Lean is a proof assistant: you write a theorem and its proof as code, and a small <strong>kernel</strong> checks every inference step. If the kernel has no bugs and only accepted axioms are used, passing the check means "this Lean statement is true." The difference from human refereeing is like the difference between a compiler with a type system and code review — the latter misses things; the former doesn't miss <em>what it checks</em>.</p>
  {{FIG_TRUST}}
  <h3>3.1 Our static audit of the Lean library <span class="tg">[P]</span></h3>
  <div class="tbl"><table>
    <thead><tr><th>Check</th><th>Result</th><th>Meaning</th></tr></thead>
    <tbody>
      <tr><td class="mono">sorry (unfinished proof)</td><td>0</td><td>no "fill in later" steps</td></tr>
      <tr><td class="mono">axiom declarations</td><td>0 (all hits are in comments)</td><td>no smuggled-in axioms</td></tr>
      <tr><td class="mono">native_decide / implemented_by / extern</td><td>0</td><td>no "trust the compiler" backdoors</td></tr>
      <tr><td class="mono">decide +kernel</td><td>≈1.31M lines, 5,848 files</td><td>large finite computations done by the kernel — still trusted, but the proofs are enormous</td></tr>
      <tr><td class="mono">Comparator configs</td><td>416, all allowing only the three standard axioms; only 2 enable the second independent kernel nanoda</td><td>see below</td></tr>
      <tr><td class="mono">lean/patches/</td><td>24 patches to third-party dependencies (not the Lean kernel, not Mathlib), largest ~2 MB</td><td>patches change definitions and proofs in dependencies ⚠</td></tr>
      <tr><td class="mono">dependencies</td><td>30, of which 11 are <code>lana-agents/*</code> repos of unknown origin</td><td>an open point in the trust chain ⚠</td></tr>
      <tr><td class="mono">formalization.yaml</td><td><code>review: status: unchecked</code></td><td>OpenAI's own label: not reviewed</td></tr>
    </tbody>
  </table></div>
  <p class="tg">Scope: lean/OAI/ has 122,458 .lean files, ~26M lines; we only grepped the source and counted configs, without compiling (a full build needs many GB of memory and a Linux sandbox). Independent re-checks: Dave Goldblatt ran the ζ 7/8 proof through Comparator and the nanoda kernel (~63 minutes) <a href="https://github.com/davegoldblatt/openai-zeta-proof-check">[repo]</a>; a third party reviewed the statement of the 9/4 matrix-multiplication theorem <a href="https://github.com/erenciracioglu-dotcom/openai-math-9-4-lean-check">[repo]</a>.</p>
  <h3>3.2 Comparator: what it guards against, and what it doesn't</h3>
  <p>The Lean FRO's <a href="https://github.com/leanprover/comparator">Comparator</a> takes a "challenge file" (only the theorem statement, with <code>sorry</code> as the proof, importing only trusted libraries such as Mathlib) and a "solution module": the theorem proven in the solution must be <strong>the same type</strong> as the challenge statement, using only allowed axioms. It guards against swapping the statement, changing definitions or adding axioms inside the proof. It does <strong>not</strong> guard against the challenge statement itself failing to say what the paper claims — and the challenge files were written by OpenAI (its agents). That is why the "verification status" of each section below focuses on <strong>reading the statement line by line</strong>.</p>
  <div class="note bug">
    <span class="label">A live counterexample</span>
    <p>A footnote in OpenAI's plane-coloring paper mentions a May 2026 manuscript that claimed the chromatic number of the plane is 7 with a "formalized theorem" — but that theorem <strong>took a false density bound as a hypothesis</strong>. The formalization was fine; the proven statement was the problem. <span class="tg">[P, as reported in the OpenAI paper; original not read ⚠]</span> This is the same kind of problem as specification gaming in AI: the system perfectly satisfies the written spec, but the spec is not what you wanted.</p>
  </div>
</section>

<section id="qrh">
  <div class="kicker">Number theory · family 003</div>
  <h2><span class="n">4.</span>The quasi-Riemann hypothesis: a ceiling on the noise in the primes</h2>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body">Count primes by hand: 25 below 100, 168 below 1000, 78,498 below 10⁶. Let π(x) = "number of primes ≤ x."</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>Prime number theorem</strong>: π(x) ≈ Li(x) = ∫₂ˣ dt/ln t. Li(10⁶) ≈ 78,626.5 vs the true 78,498 — the ratio tends to 1 (proved 1896). The real question is <strong>how big the error π(x) − Li(x) is</strong>.</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>The ζ function encodes all the primes</strong>: ζ(s) = Σ 1/nˢ = ∏ₚ 1/(1−p⁻ˢ). The identity holds because every integer factors uniquely into primes. By hand at s = 2: using only p = 2, 3, 5 gives 1.5625; all primes below 100 give 1.6419; the true value is π²/6 ≈ 1.6449.</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body">Extend s to complex numbers s = σ + it. A <strong>zero</strong> is a point where ζ(s) = 0. The non-trivial zeros all lie in the "critical strip" 0 &lt; Re s &lt; 1; the first three are at ½ + 14.13i, ½ + 21.02i, ½ + 25.01i. <strong>Riemann hypothesis (1859)</strong>: all of them lie on Re s = ½.</div></div>
    <div class="rung"><div class="lvl">Level 4</div><div class="body"><strong>Why zeros control the error</strong>: in the explicit formula each zero ρ = β + iγ contributes an "oscillating noise" term of size about x^β. All zeros with Re ≤ θ ⇒ error about x^θ. The Riemann hypothesis ⇔ error about √x. Think of the zeros as the "spectrum" of the primes, with β setting how fast each frequency's amplitude grows.</div></div>
    <div class="rung"><div class="lvl">Level 5</div><div class="body"><strong>Previously known zero-free regions</strong>: de la Vallée Poussin (1899) σ &gt; 1 − c/log t; Vinogradov–Korobov (1958) somewhat wider. <strong>Key point: their width shrinks to 0 as the height t → ∞.</strong> No one had ever proven that a <em>fixed</em> δ &gt; 0 exists with no zeros in the whole strip Re s &gt; 1 − δ.</div></div>
  </div>
  {{FIG_ZETA}}
  <h3>4.1 The problem</h3>
  <p><strong>Quasi-Riemann hypothesis</strong>: there is a fixed vertical line Re s = θ &lt; 1 with no zeros to its right. It is a weak form of the Riemann hypothesis (θ = ½), but before 2026 it was just as far out of reach.</p>
  <h3>4.2 Why it was hard</h3>
  <p>Classical methods start from positivity of the Euler product for σ &gt; 1 (e.g. the trick 3 + 4cos θ + cos 2θ ≥ 0), and that positivity weakens with height, so the regions obtained necessarily get narrower. The other route, zero-density estimates (e.g. Guth–Maynard 2024, <a href="https://arxiv.org/abs/2405.20552">arXiv:2405.20552</a>), can say "there are few zeros with Re s &gt; σ," but not "there are none." A fixed width needs a genuinely new mechanism.</p>
  <h3>4.3 What OpenAI claims</h3>
  <div class="claim"><span class="label">Claim [P]</span>
    <p><a href="''' + REPO + '''/blob/main/preprints/The-Quasi-Riemann-Hypothesis-September-30-2026/paper.pdf">Main paper</a> (2026-09-30, 199 pages): "We prove that all finite-order Hecke L-functions over Q(√−3) and all Dirichlet L-functions are zero-free in the half-plane ℜs &gt; 7/8 … In particular, the Riemann zeta function is zero-free in this half-plane." The paper stresses: "The Riemann hypothesis remains open."</p>
    <p>The family also includes a separate proof of 11/12 (49 pages, written with human assistance) and a 9-page "uniform exclusion of Landau–Siegel zeros."</p>
  </div>
  <p><strong>Method sketch</strong> (introduction only): pass to ℚ(√−3) and build a "completed sum" from Fourier coefficients of the cubic theta series, which can be evaluated two ways (a reflection formula and Poisson summation); a zero with β &gt; 7/8 would make the two estimates contradict each other. Finally the factorization L_F(s, χ∘N) = L(s,χ)·L(s,χχ₋₃) transfers the result to all Dirichlet L-functions.</p>
  <h3>4.4 Verification status</h3>
  <div class="verdict">
    <div class="panel"><h4>Machine</h4><ul>
      <li>The Lean challenge statement uses only standard Mathlib definitions, e.g. <code>theorem riemannZeta_ne_zero_of_seven_eighths_lt_re {s : ℂ} (hs : 7/8 &lt; s.re) : riemannZeta s ≠ 0</code>. <span class="tg">[P]</span></li>
      <li>Solution ~2,926 files, 487k lines; sorry/axiom/native_decide all 0. <span class="tg">[P]</span></li>
      <li>Independent re-check: Goldblatt ran it under two kernels; <code>#print axioms</code> lists only the three standard axioms. <span class="tg">[P]</span></li>
      <li>⚠ The dependency patch PrimeNumberTheoremAnd-lean4341.patch is ~40k lines and replaces two upstream sorries with proofs — part of the "dependency library" is OpenAI's own code.</li>
      <li>The paper's later applications (Section 6 corollaries) are outside the formalization.</li></ul></div>
    <div class="panel"><h4>Humans</h4><ul>
      <li>Alex Kontorovich (Rutgers; founder of the PrimeNumberTheoremAnd formalization project): "Quasi-RH?!?!???! Are you kidding me? If a human did this, it would be an instant Fields Medal…" <span class="tg">[R]</span></li>
      <li>Levent Alpöge: "Big, big, big, big props for quasiriemann and no Siegel zeroes." <span class="tg">[R]</span></li>
      <li>As of 10-08, <strong>no human expert has publicly said they read all 199 pages</strong>. ⚠</li></ul></div>
  </div>
  <p><strong>Assessment</strong>: as long as Mathlib's definition of <code>riemannZeta</code> is correct and the Lean kernel has no bug, the theorem is "proven in the machine sense" — an order of magnitude more trustworthy than an unrefereed paper. The remaining risk sits in the build chain (patches and dependencies).</p>
  <h3>4.5 If true</h3>
  <ul>
    <li><strong>A power saving in the prime number theorem</strong>: π(x) − Li(x) = O(x^(7/8) log²x). Going from "width shrinking to 0" to "fixed width" is a qualitative change; but between 7/8 and ½ everything is still unknown.</li>
    <li><strong>Siegel zeros ruled out</strong>: an obstacle that since 1935 made many constants ineffective disappears (e.g. effective lower bounds for class numbers of imaginary quadratic fields).</li>
    <li><strong>Algorithmic corollaries</strong> (paper Cor. 1.2): least quadratic non-residue ≤ C(log p)^32 ⇒ square roots mod p and the Miller primality test become <em>unconditional</em> deterministic polynomial-time algorithms. <strong>No impact on practical cryptography</strong> (randomized algorithms are used in practice, AKS 2002 already gave unconditional deterministic primality testing, and RSA and elliptic-curve security are unaffected).</li>
  </ul>
</section>

<section id="pi">
  <div class="kicker">Number theory · family 017 (+ 005)</div>
  <h2><span class="n">5.</span>How well can fractions approximate π?</h2>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body">22/7 differs from π by 1.26×10⁻³; 355/113 (Zu Chongzhi, 5th century) by only 2.67×10⁻⁷. Compare the benchmark 1/q²: 1/113² ≈ 7.8×10⁻⁵ — 355/113 beats it by nearly 300×.</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>Continued fractions</strong>: π = [3; 7, 15, 1, 292, 1, 1, …]. The larger the next term, the "unusually better" the previous truncation. 355/113 is followed by 292, which is why it is so accurate.</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>Dirichlet (1842)</strong>: every irrational number has infinitely many p/q with |x − p/q| &lt; 1/q² (pigeonhole principle). So "exponent 2" is always achievable.</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body"><strong>Irrationality exponent</strong> μ(x) = the largest ν such that |x − p/q| &lt; q^(−ν) has infinitely many solutions. Rationals: 1; Liouville numbers: ∞; <strong>algebraic irrationals (e.g. √2): exactly 2</strong> — Roth's theorem (1955), Fields Medal 1958; e: 2; almost every real number: 2. The hard part is proving it for <em>a specific number</em>.</div></div>
    <div class="rung"><div class="lvl">Level 4</div><div class="body"><strong>History of upper bounds for π</strong>: Mahler 1953: 42 → Mignotte 1974: 20 → Hata 1993: 8.016 → Salikhov 2008: 7.606 → Zeilberger–Zudilin 2020: 7.103. Seventy years took it from 42 to 7.1 — still far from 2.</div></div>
  </div>
  {{FIG_FLINT}}
  <h3>5.1 What OpenAI claims</h3>
  <div class="claim"><span class="label">Claim [P]</span>
    <p><a href="''' + REPO + '''/blob/main/preprints/The-irrationality-exponent-of-pi-is-2-September-24-2026/paper.pdf">The irrationality exponent of π is 2</a> (2026-09-24, 23 pages): "We prove the conjecture that the irrationality exponent of π is 2. As a consequence, the classical Flint–Hills series Σ 1/(n³ sin²n) converges."</p>
    <p>Precisely: for every ν &gt; 2 there is Q(ν) such that every q ≥ Q(ν) satisfies |π − p/q| ≥ q^(−ν). The paper notes that Q(ν) is <em>ineffective</em>, and that μ = 2 is not the same as "bounded partial quotients" (the stronger statement remains open).</p>
  </div>
  <p><strong>Method</strong>: suppose there are infinitely many approximations with exponent ν &gt; 2; pick several with well-separated denominators and do multivariate interpolation along a logarithmic curve to get a non-zero determinant. Arithmetically it is a non-zero integer (≥ 1); analytically the approximation errors make it tiny — contradiction. Convergence of Flint Hills then follows from an existing human result (Meiburg 2022: μ(π) &lt; 5/2 ⇒ convergence).</p>
  <p>The <strong>reasoning summary</strong> (<a href="''' + REPO + '''/blob/main/reasoning_traces/irrationality-exponent-of-pi.pdf">42 pages</a>) is worth reading: the model's initial target was only μ &lt; 5/2; it tried dozens of routes (BBP, modular forms, Padé, p-adic …), repeatedly hit a wall of "height vs denominator cost," and finally used weighted interpolation determinants to reach μ = 62/25 = 2.48 first, then 2. It also borrowed determinant ideas from its own Catalan's-constant manuscript.</p>
  <h3>5.2 Verification status</h3>
  <p>Lean: <code>lean/docs/017.md</code> and <code>ComparatorChallenges/PiExponent</code> exist; the solution is ~869 files, 95k lines, grep finds no sorry/axiom <span class="tg">[P]</span>; but it is <strong>not listed in formalization.yaml</strong> ⚠ and has no third-party re-check. The Flint Hills corollary is outside the formalization. No specific comment from number theorists found ⚠.</p>
  <div class="note">
    <span class="label">Sidebar: Catalan's constant is irrational (family 005)</span>
    <p>G = 1 − 1/3² + 1/5² − 1/7² + … ≈ 0.91597. In 1978 Apéry proved ζ(3) irrational (van der Poorten called it "A proof that Euler missed"), but the same idea fails for G: after clearing denominators the linear forms do not tend to 0. The best previous result was "at least one of β(2), β(4), …, β(10) is irrational." OpenAI claims G is irrational (44 pages) with Lean (~574k lines, also not in the yaml ⚠). If it holds, it is one of the most important single-constant irrationality results since Apéry.</p>
  </div>
  <h3>5.3 If true</h3>
  <p>For the first time a specific constant like π gets the optimal exponent that almost every real number has; the 70-year race of upper bounds ends; a Flint Hills puzzle popular for two decades is settled. Practical applications are minimal — the value is in pure mathematics, and in whether "weighted interpolation determinants" extend to constants such as ζ(3) and log 2.</p>
</section>

<section id="matmul">
  <div class="kicker">Theoretical CS · family 107</div>
  <h2><span class="n">6.</span>How fast can matrices be multiplied? ω ≤ 9/4</h2>
  <p>GPU training is, at its core, matrix multiplication. This section asks how fast it can be in principle.</p>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body">Textbook algorithm: c_ij = Σ_k a_ik·b_kj — n² entries × n multiplications each = <strong>n³</strong>. 2×2 needs 8 multiplications.</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>Strassen 1969: 2×2 with only 7 multiplications</strong> (see the code block below; check it by hand). The algorithm makes no assumption about what a…h are, so they can be matrix blocks and the algorithm can recurse: T(n) = 7T(n/2) ⇒ n^(log₂7) ≈ <strong>n^2.807</strong>. The one saved multiplication compounds at every level of recursion.</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>Definition of ω</strong>: the smallest exponent such that n×n matrix multiplication takes about n^ω operations. Clearly 2 ≤ ω ≤ 3 (lower bound 2: just reading 2n² numbers takes that many steps). The mainstream conjecture is ω = 2.</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body">"2×2 with 7 multiplications" is equivalent to "the 2×2 matrix multiplication <strong>tensor has rank</strong> ≤ 7." Then: Bini 1979 border rank → Schönhage 1981 → Strassen 1986's <strong>laser method</strong> (carving many independent matrix multiplications out of a high power of a low-rank tensor). Nearly all progress of the last 40 years came from refining the laser method.</div></div>
  </div>
<pre><code>A = [[a,b],[c,d]]   B = [[e,f],[g,h]]
M1=(a+d)(e+h)  M2=(c+d)e  M3=a(f−h)  M4=d(g−e)
M5=(a+b)h      M6=(c−a)(e+f)          M7=(b−d)(g+h)
C11=M1+M4−M5+M7   C12=M3+M5   C21=M2+M4   C22=M1−M2+M3+M6
<span class="cm"># check C12: M3+M5 = af−ah+ah+bh = af+bh ✓</span></code></pre>
  {{FIG_OMEGA}}
  <h3>6.1 What OpenAI claims</h3>
  <div class="claim"><span class="label">Claim [P]</span>
    <p><strong>An Upper Bound of 9/4 for the Matrix Multiplication Exponent</strong> (2026-10-02, <strong>only 13 pages</strong>): "We prove that the exponent of matrix multiplication over the complex numbers is at most 9/4." The method is not the laser method but Strassen's <strong>asymptotic spectrum</strong> approach: inequalities for "tensor characters" on polynomial-multiplication tensors, ending in ω ≤ 9/4. The paper says: "its proof does not specify a competitive finite matrix size."</p>
    <p>Two companions in the family: ω &lt; 2.258 over ℂ (83 pages); ω &lt; 2.371054886 over <em>every field</em>, including positive characteristic (35 pages, still in the laser-method framework, about 1.2×10⁻⁴ better than the previous record).</p>
  </div>
  <h3>6.2 Verification status</h3>
  <p><strong>Statement review</strong> <span class="tg">[P]</span>: the Lean theorem is <code>Arithmetic.omega ℂ ≤ 9/4</code>. Algorithms are modeled as straight-line programs (constant/input/+/−/× gates, each of cost 1), <code>Correct</code> requires outputting A·B for <em>all</em> input matrices, and ω is the standard non-uniform algebraic-complexity definition — consistent with the literature, no hidden assumptions. The solution directory has no sorry/axiom. <strong>Humans</strong>: Aaronson: "a <em>rational</em> exponent for once (!), and via a completely different approach" <span class="tg">[R]</span>; no public comment yet from laser-method experts (Vassilevska Williams, Alman, Le Gall) ⚠.</p>
  <h3>6.3 If true — and what it means for AI training</h3>
  <ul>
    <li><strong>In theory</strong>: solving linear systems, matrix inversion, determinants, transitive closure, bipartite matching, linear-programming solvers and more all have complexities written directly in terms of ω, and would all improve. More importantly it shows that the asymptotic-spectrum route works, making ω = 2 look closer.</li>
    <li><strong>For GPU / LLM training: essentially no direct impact.</strong> This is a classic "galactic algorithm": huge constants, advantageous only on astronomically large matrices. GPU GEMM uses n³ blocked algorithms, bottlenecked on memory bandwidth and Tensor Core throughput; even Strassen is rarely used in practice (poor numerical stability, irregular memory access).</li>
    <li><strong>How this differs from AlphaTensor / AlphaEvolve</strong>: those find low-rank decompositions of <em>fixed small sizes</em> (e.g. AlphaEvolve's 2025 4×4 complex scheme with 48 multiplications) — constant-factor optimizations that can land in real kernels. ω is about the <em>exponent</em> as n → ∞. Dupont et al. (2026-08) used AlphaEvolve to tune laser-method parameters, the first time AI touched ω, for a gain of 1.6×10⁻⁴.</li>
  </ul>
</section>

<section id="ugc">
  <div class="kicker">Theoretical CS · family 102</div>
  <h2><span class="n">7.</span>Unique Games: where is the ceiling for approximation algorithms?</h2>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body"><strong>NP-hard</strong>: problems like 3SAT and Max-Cut are believed to have no exact polynomial-time algorithms (P ≠ NP).</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>Settle for approximation.</strong> Max-Cut: split a graph's vertices into two groups to maximize edges crossing between them. A random split cuts half the edges in expectation. By hand on a triangle: the best cut has 2 edges, a random split expects 1.5, ratio 0.75.</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>Goemans–Williamson (1995)</strong>: relax each vertex to a unit vector, solve a semidefinite program (SDP), then cut with a random hyperplane — guaranteeing <strong>0.878</strong>.</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body"><strong>Approximation can be hard too</strong>: the PCP theorem (1992–98). Håstad (2001) showed approximating Max-Cut beyond 16/17 ≈ 0.941 is NP-hard. That left a 25-year gap between 0.878 and 0.941.</div></div>
    <div class="rung"><div class="lvl">Level 4</div><div class="body"><strong>Unique Games</strong>: each vertex picks one of q labels; each edge is a permutation constraint (fix one end and the other is determined). By hand: a triangle, labels {0,1,2}, constraints b=a+1, c=b+1, a=c+1 (mod 3) — going around gives a=a+3=a, fully satisfiable; change the last to a=c+2 and at most 2/3 can be satisfied. Fully satisfiable instances are solvable in polynomial time by propagating along edges; <strong>only "almost satisfiable" is hard</strong>.</div></div>
  </div>
  <p><strong>UGC (Khot 2002)</strong>: for every ε, δ &gt; 0, distinguishing "≥ 1−ε satisfiable" from "at most δ satisfiable" is NP-hard.</p>
  {{FIG_MAXCUT}}
  <h3>7.1 Why it matters so much</h3>
  <ul>
    <li><strong>KKMO 2007</strong>: if UGC holds, the limit for Max-Cut is <em>exactly</em> 0.878 — GW is optimal.</li>
    <li><strong>Khot–Regev 2008</strong>: if UGC holds, approximating Vertex Cover to 2−ε is hard.</li>
    <li><strong>Raghavendra 2008</strong>: if UGC holds, for <em>every</em> constraint satisfaction problem the basic SDP is the optimal polynomial-time approximation algorithm. One algorithm plus one conjecture fix the approximation limit of a whole class of problems.</li>
    <li>Evidence against: Arora–Barak–Steurer 2010 gave a subexponential-time algorithm for UG, which made some doubt UGC. The most recent progress was the 2018 <strong>2-to-2 theorem</strong> (Khot–Minzer–Safra et al.), proving the version with completeness about 1/2 — "half of UGC."</li>
  </ul>
  <h3>7.2 What OpenAI claims</h3>
  <div class="claim"><span class="label">Claim [P]</span>
    <p><strong>The Unique Games Theorem</strong> (2026-09-23, 58 pages): "We prove the Unique Games Conjecture. For every fixed ε, δ ∈ (0, 1/2), we give a deterministic polynomial-time reduction from 3SAT to Unique Games over a fixed finite alphabet, with completeness at least 1 − ε and soundness at most δ."</p>
    <p>The family also contains four direct reductions that <em>do not depend on UGC</em>: Max-Cut beyond 0.878 is NP-hard, Vertex Cover below 2 is NP-hard, and so on — which is what Aaronson meant when he observed (paraphrased) that UGC was not actually needed for its most famous consequences.</p>
  </div>
  <h3>7.3 Verification status</h3>
  <p><strong>Statement review</strong> <span class="tg">[P]</span>: the Lean theorem is <code>OAI.UniqueGamesTheorem.theorem11</code>. The input is a binary encoding of a 3SAT formula; the reduction must satisfy <code>Turing.TM2ComputableInPolyTime</code> (Mathlib's multi-tape Turing machines); completeness and soundness are stated cleanly, and the instances are additionally required to be "translation constraints on simple bipartite graphs" — <strong>a stronger, known-equivalent form of UGC; the encoding is faithful</strong>. Solution ~478 files, 187k lines, sorry/axiom 0.</p>
  <p><strong>Humans</strong> <span class="tg">[R]</span>: Lance Fortnow: "if they hold up, we've seen more progress in TCS in the last 24 hours than in the previous three decades combined." Mark Braverman (Quanta): "Math by press release is not that healthy for math." Dana Moshkovitz reportedly said the paper is so badly written it is impossible to read without AI help (second-hand ⚠). No public statement from Khot himself ⚠.</p>
  <h3>7.4 If true</h3>
  <p>For a large class of problems, the question "how well can efficient approximation do?" gets an exact boundary; hundreds of "if UGC then …" papers become theorems. One association for AI safety (<em>my speculation, not an established conclusion</em>): the complexity-theoretic basis of debate-style scalable oversight (Irving–Christiano–Amodei 2018) is interactive proofs and PCPs; UGC pins down the boundary of "a little error makes efficient distinction impossible," which is suggestive for protocols where a weak verifier oversees a strong prover.</p>
</section>

<section id="bpl">
  <div class="kicker">Theoretical CS · family 103 (+ 109)</div>
  <h2><span class="n">8.</span>L = RL = BPL: in small memory, randomness doesn't help</h2>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body"><strong>What does randomness buy?</strong> To test whether (x+y)² = x²+2xy+y² holds identically, plug in a few random numbers — very fast. A deterministic fast algorithm is still unknown.</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>P vs BPP</strong>: the mainstream conjecture is P = BPP (randomness gives no essential speed-up), but an unconditional proof is far away.</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>The memory-bounded version</strong>: L = deterministic computation with only O(log n) bits of memory (roughly a few pointers); RL/BPL = the same memory plus random bits. By hand: a random walk of n³ steps from s in an undirected graph needs only "current vertex + counter" and reaches t with high probability ⇒ connectivity ∈ RL (1979).</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body"><strong>History of derandomization</strong>: Nisan 1992 BPL ⊆ L² → Saks–Zhou 1999 BPL ⊆ L^(3/2) → Hoza 2021 slightly better → <strong>Reingold 2005: undirected connectivity ∈ L</strong> (a milestone in removing randomness from a specific problem). General BPL stayed near the 3/2 power for 25 years.</div></div>
  </div>
  <div class="claim"><span class="label">Claim [P]</span>
    <p><strong>Exact Derandomization of Logarithmic Space: L = RL = BPL</strong> (2026-09-23, 108 pages): "We prove L = RL = BPL, resolving the derandomization problem for polynomial-time randomized logarithmic space." A stronger version: acceptance probabilities can be estimated deterministically to precision 2^(−q) in space O(log n + q).</p>
  </div>
  <p><strong>Verification</strong> <span class="tg">[P]</span>: the Lean theorem is <code>L = RL ∧ RL = BPL</code>; for this family Comparator additionally <strong>locks 20 definitions</strong> (machine, step, space, acceptance probability, L/RL/BPL), so the solution cannot quietly change them. The model is a custom multi-tape Turing machine, space counts work cells visited, and "every coin sequence halts in polynomial time" — the standard BPL definition. sorry/axiom 0. <strong>Humans</strong> <span class="tg">[R]</span>: Aaronson called it "one of the great derandomization conjectures short of P=BPP," adding "its truth was never in serious doubt" — nobody doubted the statement; the difficulty was the proof.</p>
  <p><strong>If true</strong>: the first natural resource class with randomness removed completely and unconditionally. It does <strong>not</strong> imply P = BPP and is far from P vs NP (Fortnow: "none of these results get us any closer to settling P v NP"). The proof's "low-space, high-precision linear algebra" may matter more than the result.</p>
  <div class="note">
    <span class="label">Sidebar: integer multiplication below n log n (family 109)</span>
    <p>Schoolbook n²; Karatsuba 1962 n^1.585; Schönhage–Strassen 1971 n log n log log n, conjecturing n log n optimal; Harvey–van der Hoeven 2019 (Annals 2021) reached O(n log n). OpenAI claims O(n (log n)^(1−2^(−182))) on multi-tape Turing machines (73 pages, <strong>no Lean</strong>). A saving of 2^(−182) is visible only at astronomical sizes — no practical significance — but it refutes a 50-year "optimality" conjecture (in that model of computation).</p>
  </div>
</section>

<section id="color">
  <div class="kicker">Combinatorics · family 158 (+ 156)</div>
  <h2><span class="n">9.</span>Coloring the plane: points at distance exactly 1 must differ</h2>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body"><strong>Graph coloring</strong> (familiar from register allocation and scheduling): adjacent vertices get different colors; how many colors are needed?</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>The unit-distance graph</strong>: <em>every point</em> of the plane is a vertex; points at distance exactly 1 are joined. Its chromatic number is written χ(ℝ²).</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>Why 3 colors are not enough</strong>: the Moser spindle (figure below, 7 points). <strong>Why 7 are enough</strong>: tile the plane with hexagons of diameter slightly below 1 and color them periodically with 7 colors; same-colored hexagons are more than 1 apart.</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body">So 4 ≤ χ ≤ 7, <strong>stuck from the 1950s until 2018</strong>, when the biogerontologist Aubrey de Grey pushed the lower bound to 5 with a 1581-vertex finite graph (later shrunk to ~509 vertices by Polymath16 and SAT solvers).</div></div>
  </div>
  {{FIG_MOSER}}
  <div class="claim"><span class="label">Claim [P]</span>
    <p><strong>The Euclidean plane is not five-colorable</strong> (2026-09-23, 62 pages): "We prove that every coloring of the Euclidean plane with five colors has a monochromatic unit-distance pair, with no regularity assumption on the color classes. Consequently, the chromatic number of the plane is either six or seven."</p>
  </div>
  <p><strong>A surprising method</strong>: the standard lower-bound recipe is "find a finite graph and prove it is not k-colorable" (de Grey's route). This paper <strong>exhibits no finite graph at all</strong>, and uses ergodic theory and measure theory instead: first it proves "a genuine k-coloring exists ⇔ a 'weakly measurable' k-coloring exists" (by averaging over translations and rotations, using the <em>amenability</em> of those groups — which connects to §10), then shows no weakly measurable 5-coloring exists. The last step returns to the 1961 Moser spindle.</p>
  <p><strong>Verification</strong> <span class="tg">[P]</span>: the Lean statement is two lines a person can check at a glance:</p>
<pre><code>def ProperColoring (k) (c : ℂ → Fin k) : Prop := ∀ x y : ℂ, ‖x - y‖ = 1 → c x ≠ c y
theorem no_proper_five_coloring : ¬ ∃ c : ℂ → Fin 5, ProperColoring 5 c</code></pre>
  <p>No measurability assumption — <strong>faithful to the original problem</strong>. The proof is ~70 files, 30k lines, no sorry/axiom. Gil Kalai: "raises the lower bound to six, leaving six and seven as the two possible answers," while cautioning that "even Lean verification may have issues" <span class="tg">[R]</span>.</p>
  <p><strong>If true</strong>: χ(ℝ²) ∈ {6, 7}. A new open problem: by the de Bruijn–Erdős theorem a finite unit-distance graph needing 6 colors must exist, but nobody knows what it looks like — a good target for AI plus SAT. It is also the ideal division of labor: humans review a two-line statement, the machine checks 30,000 lines of proof.</p>
  <div class="note">
    <span class="label">Sidebar: Borsuk's conjecture fails in dimension 9 (family 156)</span>
    <p>A disk cannot be cut into 2 pieces of smaller diameter (one piece always contains an antipodal pair), but 3 pieces suffice. Borsuk asked in 1933: can every bounded set in ℝᵈ be cut into d+1 pieces of smaller diameter? Kahn–Kalai disproved it in 1993 in dimension 1325; the dimension of counterexamples later fell to 64 (2014) and 63 (2026-05, with help from GPT-5.5 Pro). OpenAI claims that the projection matrices uuᵀ of all unit vectors u in ℝ⁴, which live in a 9-dimensional space, <strong>cannot be covered by 10 pieces of smaller diameter</strong> — from 63 straight down to 9 (18 pages, with Lean). Dimensions 4–8 remain open.</p>
  </div>
</section>

<section id="thompson">
  <div class="kicker">Group theory · family 248</div>
  <h2><span class="n">10.</span>Thompson's group F: a problem "proven" and withdrawn for decades</h2>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body">A <strong>group</strong> is a set of operations that can be composed and undone. Examples: integer addition; the 8 symmetries of a square.</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>Generators</strong>: a few operations build the whole group. ℤ is generated by "+1"; the <strong>free group F₂</strong> is generated by a and b with no relations at all, and its Cayley graph is an infinite tree with 4 branches at every vertex.</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>Thompson's group F</strong>: increasing piecewise-linear maps of [0,1] to itself, with breakpoints at k/2ⁿ and slopes powers of 2; the operation is composition. Generated by x₀ (figure below) and x₁.</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body"><strong>Amenable = can you "average fairly"?</strong> Følner criterion: are there finite sets A whose proportion of change under translation by the generators is arbitrarily small? ℤ: yes; F₂: no. Von Neumann introduced the notion in 1929 to explain the <strong>Banach–Tarski paradox</strong> (a ball cut into finitely many pieces reassembled into two balls of the same size) — the paradox comes from a copy of F₂ inside the rotation group.</div></div>
    <div class="rung"><div class="lvl">Level 4</div><div class="body">"Is every non-amenable group non-amenable because it contains F₂?" No (counterexamples from the 1980s), but those counterexamples are exotic. F contains no F₂ (1985), so if F is non-amenable it is a <strong>natural, finitely presented</strong> counterexample.</div></div>
  </div>
  {{FIG_THOMPSON}}
  <h3>10.1 The best case for why Lean matters</h3>
  <p>Geoghegan conjectured in 1979 that F is non-amenable. Since then proofs have been announced in both directions: in 2009 two arXiv papers appeared almost simultaneously, Akhmedov (non-amenable) and Shavgulidze (amenable); in 2011 Moore showed the latter's errors were "serious and do not seem to be repairable" — after it had been published; <strong>Justin Moore himself claimed amenability in 2012, then withdrew after an error in Lemma 4.13 was pointed out</strong>; Akhmedov's version has never been accepted. <span class="tg">[P, arXiv 1102.0747 / 1209.2063 / 1310.4395]</span></p>
  <div class="claim"><span class="label">Claim [P]</span>
    <p><strong>Thompson's group F is nonamenable</strong> (2026-09-23, <strong>main text only 13 pages</strong>): "We prove that Thompson's group F is nonamenable. This confirms Geoghegan's conjecture."</p>
    <p>Idea: borrow a phenomenon from functional analysis — the unit ball of an infinite-dimensional Hilbert space carries a Lipschitz map that moves every point by at least ½ (Benyamini–Sternfeld 1983). If F had Følner sets, averaging over them would yield an approximate fixed point of that map — contradiction. The key tool comes from infinite-dimensional geometry, not the combinatorial counting usual in group theory.</p>
  </div>
  <p><strong>Verification</strong> <span class="tg">[P]</span>: the Lean challenge file <strong>defines F from scratch</strong> (increasing homeomorphisms, finitely many dyadic breakpoints, slopes 2^k) and an "invariant mean" (linear, positive, normalized, left-invariant); the theorem says "there is a group structure whose multiplication is composition, and no invariant mean exists." Multiplication is forced to be composition, leaving no room to cheat — <strong>faithful</strong>. Proof ~68 files, 9,500 lines, no sorry/axiom. Kalai cautiously says the paper "announces" the result <span class="tg">[R]</span>; no public comment yet from Geoghegan, Moore or Akhmedov ⚠.</p>
  <p><strong>Takeaway</strong>: the human history of this problem is a chain of "announce → find error → withdraw," including from top experts. The statement is ~60 lines of definitions a person can audit line by line; for a 13-page paper, past experience suggests the community might need years to reach consensus. Lean replaces "trust the author" with "trust the kernel and the statement."</p>
</section>

<section id="ns">
  <div class="kicker">PDE · separate September release (+ family 376)</div>
  <h2><span class="n">11.</span>Navier–Stokes: can a fluid "blow up" in finite time?</h2>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body"><strong>ODE vs PDE</strong>: an ODE's unknown is a single number changing in time, x(t); a PDE's unknown is a whole field, such as the velocity u(x,t) at every point and time — like infinitely many coupled ODEs.</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>Blowup by hand</strong> (figure below): ẋ = x², x(0) = 1 has solution 1/(1−t): 10 at t = 0.9, 100 at t = 0.99, ∞ as t → 1. The equation is perfectly smooth, yet the solution breaks in finite time. Add damping, ẋ = x² − x: small data decays, large data still blows up.</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>The NS equations</strong>: ∂ₜu + (u·∇)u − νΔu + ∇p = f, ∇·u = 0. (u·∇)u is nonlinear self-transport (the x² of the toy), νΔu is viscosity (the −x), f is external forcing.</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body"><strong>Why 3D is hard</strong>: the only global conserved quantity is energy, and under 3D scaling the energy bound controls smaller scales less and less — "supercritical." 2D is critical, which is why 2D was settled long ago.</div></div>
  </div>
  {{FIG_BLOWUP}}
  <div class="claim"><span class="label">Claim [P]</span>
    <p>"Finite time blowup for Navier–Stokes" (2026-09-08, 166 pages, plus a separate ~640k-line Lean repository <a href="https://github.com/openai/NavierStokesAndEuler">openai/NavierStokesAndEuler</a>): "For every positive viscosity, we construct a solution … that starts from rest and develops unbounded velocity in finite time while maintaining uniformly bounded kinetic energy." The forcing f is smooth and compactly supported in space-time; the paper says this establishes Clay's <strong>alternative (C) and implies (D)</strong>.</p>
  </div>
  <h3>11.1 The key detail: you choose the force</h3>
  <p>Section 2 of the paper says it plainly: "For any incompressible flow u and pressure p, we can always define the external force f to be the residual … The challenge is to choose a flow that blows up while this residual remains smooth." So (C)/(D) turns the problem into "can you build a flow that blows up while the residual force stays smooth?" — much weaker than whether the fluid blows up <em>on its own</em> (the unforced (A)/(B)). Most analysts regard (A)/(B) as the real question <span class="tg">[R]</span>. This is not cheating — (C) is a legitimate alternative written into Clay's statement — but it is <strong>a gap between specification and intent</strong>, shaped much like specification gaming in AI.</p>
  <h3>11.2 Verification and disputes</h3>
  <ul>
    <li><strong>Lean</strong> <span class="tg">[P]</span>: ~2,659 files, 640k lines, no sorry/axiom; Comparator enables the second kernel nanoda. The statement's structure matches Clay (C)/(D) (decay conditions not compared clause by clause ⚠).</li>
    <li><strong>Community</strong> <span class="tg">[R]</span>: Clay president Bridson said evaluation will be "deliberately unhurried"; Clay still lists NS as unsolved; no journal submission reported. Clay's rules require publication in a qualifying venue plus a two-year acceptance period.</li>
    <li><strong>Credit dispute</strong> <span class="tg">[R]</span>: Buckmaster and Alpöge (NYU) had forced blowup for Euler/Boussinesq in August and posted it on September 7; OpenAI acknowledged starting after hearing about their work. Fefferman (author of the Clay statement): "The heroes of the story … are Córdoba and Martínez-Zoroa" (prior work on forced Euler blowup). The first version did not cite Córdoba–Martínez-Zoroa; a revision added it. Gómez-Serrano (NPR): "The paper is not written for humans … as of today, the paper doesn't teach us much."</li>
  </ul>
  <div class="note">
    <span class="label">Related: universal computation in forced Navier–Stokes (family 376)</span>
    <p>Claim: on the 3-torus there is a smooth forcing "program" such that a fluid particle enters a target region <strong>if and only if</strong> a given Turing machine halts — so this reachability question is undecidable. The paper is candid: "There is an elementary way to force a chosen smooth incompressible velocity…" It recalls Tao's 2016 program (get the fluid itself to build a computer that hands its energy to ever-smaller copies of itself, causing blowup), but 376 puts the "programming" into the forcing and <strong>does not advance</strong> that unforced-blowup program; it does not cite Tao 2016.</p>
  </div>
  <p><strong>If true</strong>: one alternative of a Millennium Prize problem is formally closed. Almost no direct impact on weather, turbulence or engineering — engineering solvers never relied on global regularity, and real fluids hand over to molecular scales long before any singularity.</p>
</section>

<section id="vlasov">
  <div class="kicker">Mathematical physics · family 362</div>
  <h2><span class="n">12.</span>Relativistic Vlasov–Maxwell: can a plasma model break down by itself?</h2>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body"><strong>Plasma</strong>: ionized gas (fusion reactors, the solar wind). Too thin for collisions to matter, so it is described by a <strong>phase-space density</strong> f(t, x, v): how many particles are near position x with momentum v — 6 dimensions plus time.</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>Self-consistent coupling</strong>: particles feel the Lorentz force (Vlasov equation) → particles form currents → currents generate fields (Maxwell equations) → fields push particles. The nonlinearity comes from this loop.</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>Relativity</strong> (c = 1): velocity v̂ = p/√(1+p²). p = 1 gives 0.707, p = 10 gives 0.995 — momentum can be arbitrarily large, speed is always &lt; 1.</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body"><strong>Glassey–Strauss 1986</strong>: singularities can only appear at high speed — as long as particle momenta stay bounded on finite time intervals, the solution continues. The whole problem reduces to: <strong>can particles be accelerated to infinite momentum in finite time?</strong> The 40 years since produced only results with restrictions (small data, lower dimension, symmetry).</div></div>
  </div>
  {{FIG_HARMONIC}}
  <div class="claim"><span class="label">Claim [P]</span>
    <p>"Global classical solutions of the three-dimensional relativistic Vlasov–Maxwell system" (2026-09-23, 49 pages): "We prove global existence and uniqueness for arbitrary smooth admissible initial data in the three-dimensional, one-species relativistic Vlasov–Maxwell system … without size or symmetry restrictions on the data."</p>
  </div>
  <p><strong>Verification</strong> <span class="tg">[P]</span>: the hypotheses of the Lean statement <code>global_classical_solution</code> were checked one by one (f₀ smooth, compactly supported, non-negative; fields with bounded derivatives in L²; the two Gauss constraints), and the conclusion is existence + smoothness + uniqueness. ~207 files, 90k lines, no sorry/axiom. <strong>Scope limit</strong>: only <strong>one particle species</strong>, while real fusion plasmas have at least two (electrons and ions); whether the extension is routine is unclear ⚠. No named comment from plasma-PDE experts found ⚠.</p>
  <p><strong>The reasoning summary is candid</strong>: the model hit walls repeatedly ("exponent inequality contradiction: H&lt;0.41z vs H&gt;0.496z"), and its last sentence says the conclusion "rests on the occupation bound, direction-count estimate, and cutoff cancellations … the cited continuation theorem alone does not establish those estimates."</p>
  <p><strong>If true</strong>: a flagship problem open for about 40 years (one species) is solved with machine verification — possibly weightier than most results in the batch. No short-term effect on fusion engineering (PIC and gyrokinetic simulations do not depend on this theorem); what it proves is that the model does not spontaneously create particles of infinite energy — a "model health certificate."</p>
</section>

<section id="spin">
  <div class="kicker">Probability and statistical mechanics · family 221</div>
  <h2><span class="n">13.</span>Sparse spin glasses: from magnets to the energy landscapes of neural networks</h2>
  <p>This section connects directly to neuroscience and machine learning: the energy function of a Hopfield network is the Hamiltonian of a spin glass.</p>
  <div class="ladder">
    <div class="rung"><div class="lvl">Level 0</div><div class="body"><strong>Ising magnet</strong>: a spin σᵢ = ±1 at each site, energy H = −Σ Jᵢⱼσᵢσⱼ. With J &gt; 0 neighbors want to align.</div></div>
    <div class="rung"><div class="lvl">Level 1</div><div class="body"><strong>Frustration</strong> (figure, left): three spins pairwise "want" to be opposite; none of the 8 configurations satisfies all three bonds; the ground state is 6-fold degenerate.</div></div>
    <div class="rung"><div class="lvl">Level 2</div><div class="body"><strong>Spin glass</strong>: couplings Jᵢⱼ are <em>random</em> ±, frustration is everywhere, the energy landscape is rugged with exponentially many metastable states. The <strong>SK model</strong> (1975) couples every pair; <strong>Parisi (1979)</strong> gave its free energy via "replica symmetry breaking" — magical physics, not rigorous math; Guerra 2003 + Talagrand 2006 proved it rigorously; Parisi won the 2021 Nobel Prize in Physics.</div></div>
    <div class="rung"><div class="lvl">Level 3</div><div class="body"><strong>The diluted (sparse) version</strong>: each spin has only finitely many bonds. <strong>Mézard–Parisi (2001)</strong> gave a hierarchical formula via the cavity method; one direction (the upper bound) was proven in 2003–04, but <strong>equality was an open conjecture</strong>. The difficulty: in dense models pairwise overlaps describe the state; sparse models need control of all multi-replica overlaps.</div></div>
    <div class="rung"><div class="lvl">Level 4</div><div class="body"><strong>Link to random k-SAT</strong>: k-SAT is a sparse spin glass with k-body interactions. Ding–Sly–Sun (2015) rigorously proved the satisfiability threshold for large k — exactly what these physics methods predicted.</div></div>
  </div>
  {{FIG_SPIN}}
  <div class="claim"><span class="label">Claim [P]</span>
    <p>"The Mézard–Parisi formula for diluted spin glasses" (2026-09-23, 36 pages): "We prove the Mézard–Parisi hierarchical cavity formula for diluted even-arity Ising models in the Panchenko–Talagrand class." Key trick: shift every branching depth down one level and then average over depths to control multi-replica overlaps. The reasoning summary contains the line: "Aha recursive structure: overfitting shared variable can simulate original model at smaller scale."</p>
  </div>
  <p><strong>Verification</strong> <span class="tg">[P]</span>: Lean theorem <code>mezard_parisi</code> (pressure converges to the variational value), with <code>Admissible</code> spelling out the Panchenko–Talagrand hypotheses; ~405 files, 56k lines, no sorry/axiom. <strong>Narrower than the title suggests</strong>: only <strong>even-arity</strong> models with a positivity condition — odd-arity models such as 3-SAT and hard-constraint SAT at zero temperature are excluded, so it does <strong>not</strong> directly extend Ding–Sly–Sun. No named expert comment found ⚠.</p>
  <h3>13.1 Connections to ML and neuroscience (the honest version)</h3>
  <ul>
    <li><strong>Hopfield networks</strong> (1982): memories are energy minima; storage capacity was computed with the replica method (Amit–Gutfreund–Sompolinsky 1985); Hopfield and Hinton shared the 2024 Nobel Prize in Physics.</li>
    <li><strong>Perceptrons</strong>: Gardner (1988) computed capacity with replicas; family 222 in the same release gives the Ising perceptron free energy and a jamming exponent.</li>
    <li><strong>Loss landscapes</strong>: the intuition "rugged landscape with hierarchically clustered minima" comes from spin glasses (e.g. Choromanska et al. 2015). But these analogies are mostly <em>heuristic</em>; the theorem does not tell you what SGD will find.</li>
  </ul>
</section>

<section id="hodge">
  <div class="kicker">Cautionary case · family 032 and the Oct 7 withdrawals</div>
  <h2><span class="n">14.</span>One sign error, three papers withdrawn: the risk of no formalization</h2>
  <p><strong>The Hodge conjecture</strong> (a Millennium Prize problem), minimally: on a smooth projective complex algebraic variety some "topological holes" can be "filled" by subvarieties defined by algebraic equations; the conjecture says every hole satisfying a certain linear-algebra condition can be filled this way. The case p = 1 has been known since 1924 (Lefschetz).</p>
  <p>OpenAI claims the rational Hodge conjecture for all <strong>complex-multiplication (CM) abelian varieties</strong> (53 pages) — a special class, not the Millennium problem itself; like the ζ zero-free region it was <strong>not</strong> produced by the fixed procedure, and it has <strong>no Lean</strong>. <span class="tg">[P]</span></p>
  {{FIG_HODGE}}
  <h3>14.1 What happened <span class="tg">[P]</span></h3>
  <p>history.md (10-07): "In 'Algebraicity of Weil classes on split abelian eightfolds' a sign error invalidates a stabilization-trace cancellation argument and the construction used by two dependent papers." A sign that should have been −1 was taken as +1; a signed count went from the claimed 0 to −2m ≠ 0, so the hypothesis of a key theorem failed, and two dependent K3-surface papers were withdrawn with it. The CM paper does not cite the withdrawn paper and is not on this chain.</p>
  <h3>14.2 Three lessons</h3>
  <ol>
    <li><strong>Unformalized ≈ unverified</strong>: only ~42% of top-line results have Lean. This error was a single sign — missed by human eyes and the model's self-checks, and Lean would certainly have caught it.</li>
    <li><strong>Errors propagate through the dependency graph</strong>: one lemma fails, three papers fall, 13 downstream papers need new citations — the same structure as error compounding in long agent reasoning chains.</li>
    <li><strong>Title drift</strong>: family 032 was first titled "Hodge and Kuga–Satake results for all projective K3 surfaces" and only downgraded to the CM version after the withdrawals. When reading bulk AI output, trust the latest commit and history.md, not launch-day news.</li>
  </ol>
</section>

<section id="synthesis">
  <div class="kicker">Synthesis · cross-cutting view</div>
  <h2><span class="n">15.</span>The 10 results side by side</h2>
  <div class="tbl"><table>
    <thead><tr><th>Result</th><th>Previous state</th><th>Claimed jump</th><th>Statement faithful?</th><th>Confirmed by human experts</th></tr></thead>
    <tbody>
      <tr><td>Quasi-RH 7/8</td><td>no fixed-width zero-free strip at all</td><td>qualitative</td><td>yes (standard Mathlib definitions)</td><td>none</td></tr>
      <tr><td>μ(π) = 2</td><td>7.103</td><td>straight to the end</td><td>yes (not in yaml ⚠)</td><td>none</td></tr>
      <tr><td>ω ≤ 9/4</td><td>2.371177</td><td>−0.12, past a known barrier</td><td>yes</td><td>none</td></tr>
      <tr><td>UGC</td><td>"half" (2-to-2, 2018)</td><td>complete</td><td>yes (stronger form)</td><td>none</td></tr>
      <tr><td>L = BPL</td><td>near L^(3/2) for 25 years</td><td>complete</td><td>yes (definitions locked)</td><td>none</td></tr>
      <tr><td>Plane χ ≥ 6</td><td>χ ≥ 5 (2018)</td><td>+1, new method</td><td>yes (two-line statement)</td><td>none</td></tr>
      <tr><td>Thompson F</td><td>wrong proofs in both directions</td><td>resolved</td><td>yes</td><td>none</td></tr>
      <tr><td>NS blowup</td><td>forced Euler precursors</td><td>alternatives (C)/(D)</td><td>structure matches</td><td>Clay has not accepted; disputed</td></tr>
      <tr><td>Vlasov–Maxwell</td><td>40 years of restricted results</td><td>complete, one species</td><td>yes</td><td>none</td></tr>
      <tr><td>Mézard–Parisi</td><td>upper bound only</td><td>equality, even-arity class</td><td>yes (narrower than title)</td><td>none</td></tr>
    </tbody>
  </table></div>
  <h3>15.1 Five patterns</h3>
  <ol>
    <li><strong>Short statements, long proofs</strong>: plane coloring has a two-line statement and a 30k-line proof; quasi-RH a one-line statement and a 487k-line proof. This is the ideal "humans review statements, machines check proofs" split — and it makes human reviewing bandwidth the new bottleneck.</li>
    <li><strong>Unusually short papers</strong>: 13 pages for 9/4 matrix multiplication and for Thompson's group. Either the methods really are surprisingly lean, or much of the detail lives in Lean rather than in prose for humans — Gómez-Serrano said the NS paper is "not written for humans."</li>
    <li><strong>Borrowed tools across fields</strong>: Thompson's group via Lipschitz maps from infinite-dimensional geometry; plane coloring via ergodic theory; matrix multiplication via the asymptotic spectrum rather than the dominant laser method of 40 years. This may be a real AI advantage: no human-expert "field inertia."</li>
    <li><strong>The gap between "satisfying the statement" and "answering the real question"</strong>: NS with freely chosen forcing; 376 putting computation in the forcing; the plane-coloring footnote about a formalized false hypothesis; Mézard–Parisi covering only even arity. Each is "spec vs intent."</li>
    <li><strong>Selection effects</strong>: results picked from 4,000 problems vs 3% on pre-registered problems (§2.3). Until OpenAI publishes its failure list, "what is this model's real ability on open problems?" cannot be answered.</li>
  </ol>
</section>

<section id="ai">
  <div class="kicker">AI and AI safety perspective</div>
  <h2><span class="n">16.</span>What this means for AI</h2>
  <h3>16.1 Better at math ≠ smarter across the board — but a leading indicator</h3>
  <p>Mathematics has a unique advantage for AI: <strong>answers can be machine-checked</strong> (Lean), which lets reinforcement learning iterate massively — try, get feedback, improve. Chollet's question goes to the heart of it: does progress in these "verifiable domains" transfer to unverifiable ones? A reasonable reading: <strong>any intellectual work that can be automatically checked will fall at a similar pace next</strong>; mathematics is just the first.</p>
  <h3>16.2 The trust bottleneck moves from "proof" to "specification"</h3>
  <p>Once there is a Lean proof, the question shifts from "is the proof right?" to "is the statement encoded right?" This is isomorphic to a core problem in alignment research: a system can perfectly optimize the objective you wrote down, and what you wrote down may not be what you want. The line-by-line reading of Lean statements done throughout this deck is a form of <strong>spec review</strong> — an increasingly important and scarce human job.</p>
  <h3>16.3 Knowledge that can be verified but not understood</h3>
  <p>In the words of the IAS advisory group: <em>"It is now the case that AI can output mathematical arguments in situations without the human who prompted it being able to understand the arguments, verify them, or take responsibility for them."</em> <span class="tg">[R]</span> Mathematics is where this situation appears first and most cleanly (because verification is perfect). Generalized to science, humans may move from "understanders" to "checkers." Tao's Math 2.0 — putting exposition, community building and opening new directions on a par with problem-solving — is at bottom an answer to "what do humans do in this new division of labor?"</p>
  <h3>16.4 Two sides for safety research</h3>
  <div class="verdict">
    <div class="panel"><h4>Good news</h4><ul>
      <li><strong>Verifying is easier than discovering</strong>: if future AI can give formal proofs about its own behavior ("this action will not do X"), humans need not understand all of its capabilities, only check the proofs — the core idea behind the Guaranteed Safe AI agenda, which becomes more feasible as mathematical AI improves.</li>
      <li>This Lean library is itself the first real sample of "large-scale AI output + machine verification," and its failure modes can be studied.</li></ul></div>
    <div class="panel"><h4>Bad news</h4><ul>
      <li>The hardest parts of alignment ("what does this AI really want?", "is the outcome good for humans?") cannot be written in Lean. Verifiable domains racing ahead while unverifiable ones lag is itself a risk.</li>
      <li>The verifiable parts of AI R&amp;D (kernel optimization, proofs, benchmarks) will be the first to be automated at scale — the "AI improves AI" loop is most likely to start there.</li></ul></div>
  </div>
  <h3>16.5 Governance: a precedent of unilateral dumping</h3>
  <p>The community had begun forming norms through the IAS advisory group (disclose model name, prompts, reasoning chains, compute time and cost, how problems were chosen, failure rates on comparable problems). OpenAI followed some of them, then released 700+ papers at once. AHM's phrase "a demonstration of power" is pointed, but it names a structural problem: <strong>a frontier company unilaterally decides how a capability enters the public domain, and the affected community can only react afterwards</strong>.</p>
</section>

<section id="reactions">
  <div class="kicker">Reactions · in their words</div>
  <h2><span class="n">17.</span>What people said</h2>
  <div class="tbl"><table>
    <thead><tr><th>Who</th><th>Quote</th><th>Source</th></tr></thead>
    <tbody>
      <tr><td>Levent Alpöge (Anthropic)</td><td>"It's obviously the most significant moment in mathematical history." (later adding there would be "sad stories" of people being scooped)</td><td>X <span class="tg">[R]</span></td></tr>
      <tr><td>Terence Tao</td><td>"Problems are being solved autonomously by AI prompters who have no interest in the broader field itself"; proposes Math 1.0 → 2.0</td><td>Fortune <span class="tg">[R]</span></td></tr>
      <tr><td>Dan Litt (Toronto)</td><td>"My view is that this is great for mathematics," while worrying that an "AI has solved math" perception could discourage young people</td><td>Fortune <span class="tg">[R]</span></td></tr>
      <tr><td>Tristan Buckmaster (NYU)</td><td>"There's likely to be a bunch of results where they take someone's work and then take it to completion"</td><td>Fortune <span class="tg">[R]</span></td></tr>
      <tr><td>Scott Aaronson</td><td>Post "The Mathocalypse"; on L = BPL: "its truth was never in serious doubt"</td><td><a href="https://scottaaronson.blog/?p=10169">blog</a> <span class="tg">[R]</span></td></tr>
      <tr><td>Lance Fortnow</td><td>"if they hold up, we've seen more progress in TCS in the last 24 hours than in the previous three decades combined"</td><td>Computational Complexity blog <span class="tg">[R]</span></td></tr>
      <tr><td>Mark Braverman</td><td>"Math by press release is not that healthy for math."</td><td>Quanta <span class="tg">[R]</span></td></tr>
      <tr><td>François Chollet</td><td>Asks whether gains in RLVR-friendly domains generalize, or whether non-verifiable domains stay bottlenecked on human data</td><td>X (paraphrase) <span class="tg">[R]</span></td></tr>
      <tr><td>AHM</td><td>"Releasing over 700 files at once is not a demonstration of scholarship, but a demonstration of power."; urges mathematicians to stop working with OpenAI</td><td><a href="https://terrytao.wordpress.com/2026/10/07/ahm-statement-on-openais-october-6-release-of-mathematical-documents/">reposted on Tao's blog</a> (Tao notes he does not endorse it) <span class="tg">[P]</span></td></tr>
      <tr><td>Álvaro Lozano-Robledo</td><td>"Keep calm and carry on studying math."; LLMs "may work within the confines of the convex hull of ideas that are currently available in the literature"</td><td><a href="https://terrytao.wordpress.com/2026/10/08/what-should-we-tell-our-students/">guest post on Tao's blog</a> <span class="tg">[P]</span></td></tr>
      <tr><td>Andrew Sutherland (MIT)</td><td>"We should ask for receipts."</td><td>via Scientific American <span class="tg">[R]</span></td></tr>
    </tbody>
  </table></div>
  <p class="tg">Note: "The Future of Mathematics" on Tao's blog (10-05) is a guest post by Jeremy Avigad, not by Tao; some coverage conflated the two.</p>
</section>

<section id="learn">
  <div class="kicker">Next steps</div>
  <h2><span class="n">18.</span>Open questions and how to keep learning</h2>
  <h3>18.1 What to watch</h3>
  <ol>
    <li>Will OpenAI publish the list of ~4,000 problems and the failures? (This decides whether "what is the real capability?" can be answered.)</li>
    <li>How many errors like the Weil-class paper remain in the ~58% that is unformalized? How will the withdrawal rate evolve?</li>
    <li>Who reviews the faithfulness of the Lean statements? When does <code>review: unchecked</code> change? Who audits the <code>lana-agents</code> dependencies and the large patches?</li>
    <li>When will the first human domain expert give an independent "read and confirmed" verdict on a headline result (quasi-RH, UGC, Thompson F)?</li>
    <li>What priority norms should govern "completing someone else's work" (the Buckmaster episode)?</li>
    <li>Chromatic number of the plane: what does a finite unit-distance graph needing 6 colors look like?</li>
  </ol>
  <h3>18.2 Learning path (starting from linear algebra + calculus)</h3>
  <div class="tbl"><table>
    <thead><tr><th>Stage</th><th>Material</th><th>Why</th></tr></thead>
    <tbody>
      <tr><td>1 · What math is</td><td>Gowers, <em>Mathematics: A Very Short Introduction</em></td><td>150 pages by a Fields medalist: abstraction, proof, what "hard" means</td></tr>
      <tr><td>1 · Roots of this debate</td><td>Thurston, <a href="https://arxiv.org/abs/math/9404236">On Proof and Progress in Mathematics</a>; Gowers, <a href="https://www.dpmms.cam.ac.uk/~wtg10/2cultures.pdf">The Two Cultures of Mathematics</a>; Tao, <a href="https://arxiv.org/abs/math/0702396">What is good mathematics?</a></td><td>after these, "Math 1.0 → 2.0" makes complete sense</td></tr>
      <tr><td>2 · Touch a proof</td><td>Natural Number Game (Kevin Buzzard, free online)</td><td>prove commutativity of addition from scratch in Lean — then §3 makes full sense</td></tr>
      <tr><td>2 · Learn proofs systematically</td><td>MIT 6.042 Mathematics for Computer Science (OCW + free textbook)</td><td>designed for CS backgrounds: proof methods, discrete math, probability</td></tr>
      <tr><td>3 · Intuition</td><td>3Blue1Brown: <em>Essence of linear algebra</em>; visualizing the Riemann zeta function</td><td>the figure in §4 is a static version of that episode</td></tr>
      <tr><td>3 · Following the news</td><td>Quanta Magazine (math); <em>The Princeton Companion to Mathematics</em> (as a reference)</td><td>every piece explains why a problem is hard and where people were stuck</td></tr>
      <tr><td>4 · ML-adjacent</td><td>Bubeck, <a href="https://arxiv.org/abs/1405.4980">Convex Optimization: Algorithms and Complexity</a>; Prince, <em>Understanding Deep Learning</em> (free)</td><td>convergence proofs for optimization; intro to deep-learning theory</td></tr>
    </tbody>
  </table></div>
</section>

<section id="sources">
  <div class="kicker">Glossary and sources</div>
  <h2><span class="n">19.</span>Glossary and sources</h2>
  <h3>19.1 Glossary</h3>
  <div class="tbl"><table>
    <thead><tr><th>Term</th><th>In one line</th></tr></thead>
    <tbody>
      <tr><td class="mono">Lean / Mathlib</td><td>a proof assistant / its community math library</td></tr>
      <tr><td class="mono">sorry / axiom</td><td>in Lean: "leave this step empty" / "assume this is true" — both weaken a proof</td></tr>
      <tr><td class="mono">Comparator</td><td>tool checking "the theorem proven = the challenge statement, using only allowed axioms"</td></tr>
      <tr><td class="mono">zero-free region</td><td>a region where ζ or an L-function has no zeros</td></tr>
      <tr><td class="mono">irrationality exponent μ</td><td>how "unusually well" a number can be approximated by fractions</td></tr>
      <tr><td class="mono">ω</td><td>the optimal exponent of matrix multiplication, 2 ≤ ω ≤ 3</td></tr>
      <tr><td class="mono">approximation ratio</td><td>the fraction of the optimum a polynomial-time algorithm guarantees</td></tr>
      <tr><td class="mono">L / RL / BPL</td><td>log-space deterministic / one-sided randomized / two-sided randomized computation</td></tr>
      <tr><td class="mono">amenable</td><td>a group admits a translation-invariant "average"</td></tr>
      <tr><td class="mono">blowup</td><td>a solution of a smooth equation going to infinity in finite time</td></tr>
      <tr><td class="mono">replica symmetry breaking (RSB)</td><td>Parisi's description of the hierarchical state structure of spin glasses</td></tr>
      <tr><td class="mono">galactic algorithm</td><td>asymptotically faster, but only better at astronomical sizes</td></tr>
    </tbody>
  </table></div>
  <h3>19.2 Main sources</h3>
  <p><strong>Primary</strong>: <a href="''' + REPO + '''">openai/math</a> (README, history.md, overview.pdf, CONTENTS.md, lean/, preprints/, reasoning_traces/; snapshot fd4aeeb, 2026-10-08) · <a href="https://github.com/openai/NavierStokesAndEuler">openai/NavierStokesAndEuler</a> · <a href="https://www.claymath.org/wp-content/uploads/2022/06/navierstokes.pdf">Clay NS official statement (Fefferman)</a> · <a href="https://github.com/leanprover/comparator">leanprover/comparator</a> · independent re-checks <a href="https://github.com/davegoldblatt/openai-zeta-proof-check">davegoldblatt/openai-zeta-proof-check</a>, <a href="https://github.com/erenciracioglu-dotcom/openai-math-9-4-lean-check">erenciracioglu-dotcom/openai-math-9-4-lean-check</a> · Epoch <a href="https://arxiv.org/abs/2609.25050">FrontierMath Erdős (arXiv:2609.25050)</a>.</p>
  <p><strong>Coverage and commentary</strong>: <a href="https://fortune.com/2026/10/07/openai-math-controversy-solutions-370-outstanding-challenges-published-criticisms-celebration/">Fortune 10-07</a> · <a href="https://www.nature.com/articles/d41586-026-03196-8">Nature</a> (paywalled, full text not read ⚠) · <a href="https://www.scientificamerican.com/article/openai-unleashes-hundreds-more-math-results-upon-a-field-already-in-shock/">Scientific American</a> · <a href="https://www.quantamagazine.org/ai-has-solved-one-of-maths-1-million-millennium-prize-problems-20260908/">Quanta 09-08</a> · <a href="https://www.quantamagazine.org/as-ai-closed-in-on-unique-games-proof-researchers-raced-to-beat-the-machines-20261007/">Quanta 10-07</a> · <a href="https://www.npr.org/2026/09/22/nx-s1-5968588/openai-navier-stokes-problem-mathematicians-learn-little">NPR 09-22</a> · <a href="https://scottaaronson.blog/?p=10169">Aaronson</a> · <a href="https://gilkalai.wordpress.com/2026/10/07/updates-sharing-ai-progress-on-mathematics-amazing-and-my-lecture-plans/">Kalai</a> · <a href="https://terrytao.wordpress.com/">Tao's blog</a> · <a href="https://www.latent.space/p/ainews-quasi-riemann-hypothesis-openai">Latent Space</a>.</p>
  <p><strong>Classic references</strong>: Strassen 1969; Coppersmith–Winograd 1990; Alman et al. <a href="https://arxiv.org/abs/2404.16349">arXiv:2404.16349</a>; Ambainis–Filmus–Le Gall <a href="https://arxiv.org/abs/1411.5414">arXiv:1411.5414</a>; Goemans–Williamson 1995; Khot 2002; KKMO 2007; Raghavendra 2008; Khot–Minzer–Safra 2018; Nisan 1992; Saks–Zhou 1999; Reingold 2008; Roth 1955; Zeilberger–Zudilin <a href="https://arxiv.org/abs/1912.06345">arXiv:1912.06345</a>; Meiburg <a href="https://arxiv.org/abs/2208.13356">arXiv:2208.13356</a>; Guth–Maynard <a href="https://arxiv.org/abs/2405.20552">arXiv:2405.20552</a>; de Grey <a href="https://arxiv.org/abs/1804.02385">arXiv:1804.02385</a>; Moore <a href="https://arxiv.org/abs/1102.0747">arXiv:1102.0747</a>; Tao 2016 <a href="https://arxiv.org/abs/1402.0290">arXiv:1402.0290</a>; Glassey–Strauss 1986; Parisi 1979; Talagrand 2006; Mézard–Parisi 2001; Ding–Sly–Sun 2015.</p>
</section>
'''

FIGS = {
    "{{FIG_FIELDS}}": figs.svg_fields(), "{{FIG_TRUST}}": figs.svg_trust(), "{{FIG_ZETA}}": figs.svg_zeta(),
    "{{FIG_FLINT}}": figs.svg_flint(), "{{FIG_OMEGA}}": figs.svg_omega(), "{{FIG_MAXCUT}}": figs.svg_maxcut(),
    "{{FIG_MOSER}}": figs.svg_moser(), "{{FIG_THOMPSON}}": figs.svg_thompson(), "{{FIG_BLOWUP}}": figs.svg_blowup(),
    "{{FIG_HARMONIC}}": figs.svg_harmonic(), "{{FIG_SPIN}}": figs.svg_spin(), "{{FIG_HODGE}}": figs.svg_hodge(),
}
import re as _re
while _re.search(r'\^\{([^{}]*)\}', BODY):
    BODY = _re.sub(r'\^\{([^{}]*)\}', r'^(\1)', BODY)
for k, v in FIGS.items():
    assert k in BODY, k
    BODY = BODY.replace(k, v)

toc_html = "\n".join(f'  <a href="#{i}"><span class="num">{n}</span>{t}</a>' for i, n, t in TOC)

HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>OpenAI Math Release, Explained</title>
<style>
""" + CSS + EXTRA_CSS + """
</style>
</head>
<body>
<div class="page">
<nav class="toc">
""" + toc_html + """
</nav>
<main>
""" + BODY + """
</main>
</div>
<script>
(() => {
  const links = [...document.querySelectorAll('nav.toc a')];
  const sections = links.map(a => document.querySelector(a.getAttribute('href'))).filter(Boolean);
  const io = new IntersectionObserver((entries) => {
    entries.forEach(e => {
      if (!e.isIntersecting) return;
      const id = '#' + e.target.id;
      links.forEach(l => l.classList.toggle('active', l.getAttribute('href') === id));
    });
  }, { rootMargin: '-40% 0px -50% 0px', threshold: 0 });
  sections.forEach(s => io.observe(s));
})();
</script>
</body>
</html>
"""

out = ROOT / "notes_en.html"
out.write_text(HTML)
print(f"wrote {out} ({len(HTML)} bytes)")
